#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генератор Resources/<язык>.lproj/Localizable.strings.

    python3 Tools/make-strings.py

Единственный источник правды по переводам. Английский — запасной язык
(CFBundleDevelopmentRegion), из него же берутся значения для ключей,
которых нет в конкретном переводе.

Единицы времени намеренно сокращены: так строки не зависят от правил
множественного числа, которые в русском, польском и украинском разные.
Только LTR-языки — зеркалить макет панели не требуется.
"""
import io
import os

ORDER = [
    ("Окна лимитов и время", [
        "reset.days", "reset.hours", "reset.minutes", "reset.imminent",
        "age.justNow", "age.seconds", "age.minutes", "age.hours", "age.days",
        "window.fiveHour", "window.week", "window.hours", "window.days",
        "window.generic", "format.percent",
    ]),
    ("Колонка", [
        "column.updating", "column.stale",
        "column.reauth", "column.reauth.help",
    ]),
    ("Панель", [
        "panel.updated", "panel.noData", "panel.refresh.help",
        "panel.empty.title", "panel.empty.hint",
        "panel.hidden.title", "panel.hidden.hint",
    ]),
    ("Контекстное меню", [
        "menu.refresh", "menu.addClaude", "menu.addCodex", "menu.hideColumn",
        "menu.noColumns", "menu.renameColumn", "menu.removeColumn", "menu.showHidden",
        "menu.hotKey", "menu.hotKey.change", "menu.hotKey.standard", "menu.hotKey.disable",
        "menu.loginItem", "menu.about", "menu.quit",
    ]),
    ("Удаление аккаунта", [
        "remove.title", "remove.body", "remove.delete", "remove.failed.title",
        "remove.incomplete",
    ]),
    ("Обновления", [
        "menu.checkUpdates", "update.available", "update.availableBody",
        "update.open", "update.upToDate", "update.failed",
        "update.install", "update.installing", "update.installFailed",
        "update.err.noAsset", "update.err.download", "update.err.checksum",
        "update.err.unpack", "update.err.notWritable",
    ]),
    ("Горячая клавиша", [
        "hotkey.disabled", "hotkey.recorder.title", "hotkey.recorder.hint",
        "hotkey.recorder.save", "hotkey.taken.title", "hotkey.taken.body",
    ]),
    ("Переименование колонки", ["rename.title", "rename.hint"]),
    ("Общее", ["common.ok", "common.cancel", "common.save"]),
    ("Добавление аккаунта", [
        "setup.claude.title", "setup.codex.title", "setup.profile.hint",
        "setup.profile.terminal", "setup.profile.folder",
        "setup.profile.main", "setup.profile.mainReplaces",
        "setup.profile.badChars", "setup.profile.exists", "setup.create",
        "setup.badName.title", "setup.badName.body", "setup.failed.title",
        "setup.missing.title", "setup.missing.body",
        "setup.script.profile", "setup.script.hint", "setup.script.relogin", "setup.script.reauth",
        "loginItem.failed.title",
    ]),
    ("Статистика под окнами", [
        "stat.credits", "stat.unlimited", "stat.resetCredits", "stat.extraUsage",
    ]),
    ("Прогноз исчерпания", ["burn.limitAt"]),
    ("Уведомления", ["notification.title", "notification.body",
                     "notification.reset.title", "notification.reset.body"]),
    ("Ошибки в колонке", [
        "error.network", "error.keychainWrite", "error.timeout", "error.noHTTP", "error.http",
        "error.parse", "error.unknownSource", "error.noProvider",
        "error.unreachable",
    ]),
    ("Переключение приложений", [
        "appswitch.title", "appswitch.title.codex", "appswitch.confirm.title",
        "appswitch.confirm.body", "appswitch.confirm.do", "appswitch.error.title",
        "appswitch.error.notInstalled", "appswitch.error.didNotQuit",
        "appswitch.error.noAuth",
    ]),
]

T = {}

T["en"] = {
    "reset.days": "Resets in %1$dd %2$dh",
    "reset.hours": "Resets in %1$dh %2$dm",
    "reset.minutes": "Resets in %dm",
    "reset.imminent": "Resetting now",
    "age.justNow": "just now",
    "age.seconds": "%ds ago", "age.minutes": "%dm ago",
    "age.hours": "%dh ago", "age.days": "%dd ago",
    "window.fiveHour": "5-hour window", "window.week": "Weekly window",
    "window.hours": "%d-hour window", "window.days": "%d-day window",
    "window.generic": "Limit window", "format.percent": "%d%%",
    "column.updating": "refreshing…", "column.stale": "data from %@",
    "panel.updated": "Updated %@", "panel.noData": "No data yet",
    "panel.refresh.help": "Refresh all columns",
    "panel.empty.title": "No accounts",
    "panel.empty.hint": "Right-click → “Add Claude account…” or “Add Codex account…”",
    "panel.hidden.title": "All columns hidden",
    "panel.hidden.hint": "Right-click → “Show hidden columns”",
    "menu.refresh": "Refresh", "menu.addClaude": "Add Claude account…",
    "menu.addCodex": "Add Codex account…", "menu.hideColumn": "Hide column",
    "menu.noColumns": "No columns", "menu.showHidden": "Show hidden columns",
    "menu.renameColumn": "Rename column",
    "rename.title": "Column name",
    "rename.hint": "How this column is labelled. Leave empty to go back to “%@”.",
    "common.save": "Save",
    "menu.hotKey": "Shortcut: %@", "menu.hotKey.change": "Change…",
    "menu.hotKey.standard": "Default (⌘P)", "menu.hotKey.disable": "Turn off",
    "menu.loginItem": "Launch at login", "menu.quit": "Quit",
    "hotkey.disabled": "off", "hotkey.recorder.title": "Shortcut",
    "hotkey.recorder.hint": "Press a combination — it must include ⌘, ⌥ or ⌃.",
    "hotkey.recorder.save": "Save",
    "hotkey.taken.title": "%@ is already taken",
    "hotkey.taken.body": "Another app already holds it. Your previous shortcut is unchanged.",
    "common.ok": "OK", "common.cancel": "Cancel",
    "setup.claude.title": "New Claude account",
    "setup.codex.title": "New Codex account",
    "setup.profile.hint": "Pick a short name for this account — for example work or personal. It becomes the column heading, and the CLI keeps its settings in a folder of that name.",
    "setup.profile.terminal": "After you click Create, Terminal opens — sign in there.",
    "setup.profile.folder": "Folder: %@",
    "setup.profile.badChars": "Latin letters, digits, hyphen and underscore only.",
    "setup.profile.exists": "A profile with this name already exists.",
    "setup.create": "Create", "setup.badName.title": "Bad profile name",
    "setup.badName.body": "Latin letters, digits, hyphen and underscore only. The name must not be empty or already taken.",
    "setup.failed.title": "Could not create the profile",
    "setup.missing.title": "Couldn’t find %@",
    "setup.missing.body": "Install the CLI and try again:\\n\\n%@",
    "setup.script.profile": "Profile: %@",
    "setup.script.hint": "Sign in, then close this window.",
    "loginItem.failed.title": "Could not change launch at login",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "network error", "error.timeout": "timeout",
    "error.noHTTP": "no HTTP response", "error.http": "HTTP %d",
    "error.parse": "could not parse response",
    "error.unknownSource": "unknown source", "error.noProvider": "no provider",
    "error.unreachable": "network unavailable",
}

T["ru"] = {
    "reset.days": "Сброс через %1$d д %2$d ч",
    "reset.hours": "Сброс через %1$d ч %2$d мин",
    "reset.minutes": "Сброс через %d мин",
    "reset.imminent": "Сброс вот-вот",
    "age.justNow": "только что",
    "age.seconds": "%d с назад", "age.minutes": "%d мин назад",
    "age.hours": "%d ч назад", "age.days": "%d д назад",
    "window.fiveHour": "5-часовое окно", "window.week": "Недельное окно",
    "window.hours": "%d-часовое окно", "window.days": "%d-дневное окно",
    "window.generic": "Окно лимита", "format.percent": "%d %%",
    "column.updating": "обновляю…", "column.stale": "данные %@",
    "panel.updated": "Обновлено %@", "panel.noData": "Данных ещё нет",
    "panel.refresh.help": "Обновить все колонки",
    "panel.empty.title": "Нет аккаунтов",
    "panel.empty.hint": "Правый клик → «Добавить аккаунт Claude…» или «Добавить аккаунт Codex…»",
    "panel.hidden.title": "Все колонки скрыты",
    "panel.hidden.hint": "Правый клик → «Показать скрытые колонки»",
    "menu.refresh": "Обновить", "menu.addClaude": "Добавить аккаунт Claude…",
    "menu.addCodex": "Добавить аккаунт Codex…", "menu.hideColumn": "Скрыть колонку",
    "menu.noColumns": "Нет колонок", "menu.showHidden": "Показать скрытые колонки",
    "menu.renameColumn": "Переименовать колонку",
    "rename.title": "Имя колонки",
    "rename.hint": "Как подписать эту колонку. Пусто — вернуть «%@».",
    "common.save": "Сохранить",
    "menu.hotKey": "Горячая клавиша: %@", "menu.hotKey.change": "Изменить…",
    "menu.hotKey.standard": "Стандартная (⌘P)", "menu.hotKey.disable": "Выключить",
    "menu.loginItem": "Запуск при входе", "menu.quit": "Выход",
    "hotkey.disabled": "выключена", "hotkey.recorder.title": "Горячая клавиша",
    "hotkey.recorder.hint": "Нажми сочетание — обязательно с ⌘, ⌥ или ⌃.",
    "hotkey.recorder.save": "Сохранить",
    "hotkey.taken.title": "Сочетание %@ занято",
    "hotkey.taken.body": "Его уже держит другое приложение. Прежняя настройка осталась без изменений.",
    "common.ok": "Ок", "common.cancel": "Отмена",
    "setup.claude.title": "Новый аккаунт Claude",
    "setup.codex.title": "Новый аккаунт Codex",
    "setup.profile.hint": "Придумай короткое имя для этого аккаунта — например work или personal. Оно станет заголовком колонки, а CLI будет держать настройки в папке с таким именем.",
    "setup.profile.terminal": "После «Создать» откроется Терминал — вход в аккаунт делается там.",
    "setup.profile.folder": "Папка: %@",
    "setup.profile.badChars": "Только латиница, цифры, дефис и подчёркивание.",
    "setup.profile.exists": "Профиль с таким именем уже есть.",
    "setup.create": "Создать", "setup.badName.title": "Плохое имя профиля",
    "setup.badName.body": "Только латиница, цифры, дефис и подчёркивание. Имя не должно быть пустым или уже занятым.",
    "setup.failed.title": "Не получилось создать профиль",
    "setup.missing.title": "Не нашёл %@",
    "setup.missing.body": "Установи CLI и попробуй снова:\\n\\n%@",
    "setup.script.profile": "Профиль: %@",
    "setup.script.hint": "Войди в аккаунт, затем закрой это окно.",
    "loginItem.failed.title": "Не получилось изменить запуск при входе",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "сбой сети", "error.timeout": "таймаут",
    "error.noHTTP": "нет HTTP-ответа", "error.http": "HTTP %d",
    "error.parse": "не разобрал ответ",
    "error.unknownSource": "неизвестный источник", "error.noProvider": "нет провайдера",
    "error.unreachable": "сеть недоступна",
}

T["de"] = {
    "reset.days": "Zurücksetzung in %1$d T %2$d Std",
    "reset.hours": "Zurücksetzung in %1$d Std %2$d Min",
    "reset.minutes": "Zurücksetzung in %d Min",
    "reset.imminent": "Wird gerade zurückgesetzt",
    "age.justNow": "gerade eben",
    "age.seconds": "vor %d s", "age.minutes": "vor %d Min",
    "age.hours": "vor %d Std", "age.days": "vor %d T",
    "window.fiveHour": "5-Stunden-Fenster", "window.week": "Wochenfenster",
    "window.hours": "%d-Stunden-Fenster", "window.days": "%d-Tage-Fenster",
    "window.generic": "Limitfenster", "format.percent": "%d %%",
    "column.updating": "wird aktualisiert…", "column.stale": "Daten von %@",
    "panel.updated": "Aktualisiert %@", "panel.noData": "Noch keine Daten",
    "panel.refresh.help": "Alle Spalten aktualisieren",
    "panel.empty.title": "Keine Accounts",
    "panel.empty.hint": "Rechtsklick → „Claude-Account hinzufügen…“ oder „Codex-Account hinzufügen…“",
    "panel.hidden.title": "Alle Spalten ausgeblendet",
    "panel.hidden.hint": "Rechtsklick → „Ausgeblendete Spalten zeigen“",
    "menu.refresh": "Aktualisieren", "menu.addClaude": "Claude-Account hinzufügen…",
    "menu.addCodex": "Codex-Account hinzufügen…", "menu.hideColumn": "Spalte ausblenden",
    "menu.noColumns": "Keine Spalten", "menu.showHidden": "Ausgeblendete Spalten zeigen",
    "menu.renameColumn": "Spalte umbenennen",
    "rename.title": "Spaltenname",
    "rename.hint": "Wie diese Spalte beschriftet wird. Leer lassen, um zu „%@“ zurückzukehren.",
    "common.save": "Sichern",
    "menu.hotKey": "Tastenkürzel: %@", "menu.hotKey.change": "Ändern…",
    "menu.hotKey.standard": "Standard (⌘P)", "menu.hotKey.disable": "Ausschalten",
    "menu.loginItem": "Beim Anmelden starten", "menu.quit": "Beenden",
    "hotkey.disabled": "aus", "hotkey.recorder.title": "Tastenkürzel",
    "hotkey.recorder.hint": "Drücke eine Kombination — mit ⌘, ⌥ oder ⌃.",
    "hotkey.recorder.save": "Sichern",
    "hotkey.taken.title": "%@ ist bereits belegt",
    "hotkey.taken.body": "Eine andere App belegt es bereits. Die vorherige Einstellung bleibt unverändert.",
    "common.ok": "OK", "common.cancel": "Abbrechen",
    "setup.claude.title": "Neuer Claude-Account",
    "setup.codex.title": "Neuer Codex-Account",
    "setup.profile.hint": "Wähle einen kurzen Namen für diesen Account — etwa work oder personal. Er wird zur Spaltenüberschrift, und das CLI legt seine Einstellungen in einem Ordner dieses Namens ab.",
    "setup.profile.terminal": "Nach „Erstellen“ öffnet sich das Terminal — melde dich dort an.",
    "setup.profile.folder": "Ordner: %@",
    "setup.profile.badChars": "Nur lateinische Buchstaben, Ziffern, Bindestrich und Unterstrich.",
    "setup.profile.exists": "Ein Profil mit diesem Namen existiert bereits.",
    "setup.create": "Erstellen", "setup.badName.title": "Ungültiger Profilname",
    "setup.badName.body": "Nur lateinische Buchstaben, Ziffern, Bindestrich und Unterstrich. Der Name darf nicht leer oder schon vergeben sein.",
    "setup.failed.title": "Profil konnte nicht erstellt werden",
    "setup.missing.title": "%@ nicht gefunden",
    "setup.missing.body": "Installiere das CLI und versuche es erneut:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Melde dich an und schliesse dieses Fenster.",
    "loginItem.failed.title": "Anmeldeobjekt konnte nicht geändert werden",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "Netzwerkfehler", "error.timeout": "Zeitüberschreitung",
    "error.noHTTP": "keine HTTP-Antwort", "error.http": "HTTP %d",
    "error.parse": "Antwort nicht lesbar",
    "error.unknownSource": "unbekannte Quelle", "error.noProvider": "kein Anbieter",
    "error.unreachable": "Netzwerk nicht verfügbar",
}

T["fr"] = {
    "reset.days": "Réinitialisation dans %1$d j %2$d h",
    "reset.hours": "Réinitialisation dans %1$d h %2$d min",
    "reset.minutes": "Réinitialisation dans %d min",
    "reset.imminent": "Réinitialisation imminente",
    "age.justNow": "à l’instant",
    "age.seconds": "il y a %d s", "age.minutes": "il y a %d min",
    "age.hours": "il y a %d h", "age.days": "il y a %d j",
    "window.fiveHour": "Fenêtre de 5 h", "window.week": "Fenêtre hebdomadaire",
    "window.hours": "Fenêtre de %d h", "window.days": "Fenêtre de %d j",
    "window.generic": "Fenêtre de limite", "format.percent": "%d %%",
    "column.updating": "actualisation…", "column.stale": "données %@",
    "panel.updated": "Mis à jour %@", "panel.noData": "Pas encore de données",
    "panel.refresh.help": "Actualiser toutes les colonnes",
    "panel.empty.title": "Aucun compte",
    "panel.empty.hint": "Clic droit → « Ajouter un compte Claude… » ou « Ajouter un compte Codex… »",
    "panel.hidden.title": "Toutes les colonnes sont masquées",
    "panel.hidden.hint": "Clic droit → « Afficher les colonnes masquées »",
    "menu.refresh": "Actualiser", "menu.addClaude": "Ajouter un compte Claude…",
    "menu.addCodex": "Ajouter un compte Codex…", "menu.hideColumn": "Masquer une colonne",
    "menu.noColumns": "Aucune colonne", "menu.showHidden": "Afficher les colonnes masquées",
    "menu.renameColumn": "Renommer la colonne",
    "rename.title": "Nom de la colonne",
    "rename.hint": "Le libellé de cette colonne. Laissez vide pour revenir à « %@ ».",
    "common.save": "Enregistrer",
    "menu.hotKey": "Raccourci : %@", "menu.hotKey.change": "Modifier…",
    "menu.hotKey.standard": "Par défaut (⌘P)", "menu.hotKey.disable": "Désactiver",
    "menu.loginItem": "Lancer à l’ouverture de session", "menu.quit": "Quitter",
    "hotkey.disabled": "désactivé", "hotkey.recorder.title": "Raccourci",
    "hotkey.recorder.hint": "Appuyez sur une combinaison — avec ⌘, ⌥ ou ⌃.",
    "hotkey.recorder.save": "Enregistrer",
    "hotkey.taken.title": "%@ est déjà utilisé",
    "hotkey.taken.body": "Une autre app l’utilise déjà. Votre réglage précédent est conservé.",
    "common.ok": "OK", "common.cancel": "Annuler",
    "setup.claude.title": "Nouveau compte Claude",
    "setup.codex.title": "Nouveau compte Codex",
    "setup.profile.hint": "Choisissez un nom court pour ce compte — par exemple work ou personal. Il servira de titre de colonne, et le CLI rangera ses réglages dans un dossier de ce nom.",
    "setup.profile.terminal": "Après « Créer », le Terminal s’ouvre — connectez-vous là.",
    "setup.profile.folder": "Dossier : %@",
    "setup.profile.badChars": "Lettres latines, chiffres, tiret et tiret bas uniquement.",
    "setup.profile.exists": "Un profil de ce nom existe déjà.",
    "setup.create": "Créer", "setup.badName.title": "Nom de profil invalide",
    "setup.badName.body": "Lettres latines, chiffres, tiret et tiret bas uniquement. Le nom ne doit être ni vide ni déjà pris.",
    "setup.failed.title": "Impossible de créer le profil",
    "setup.missing.title": "Impossible de trouver %@",
    "setup.missing.body": "Installez le CLI puis réessayez :\\n\\n%@",
    "setup.script.profile": "Profil : %@",
    "setup.script.hint": "Connectez-vous, puis fermez cette fenetre.",
    "loginItem.failed.title": "Impossible de modifier le lancement à l’ouverture",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@ : %2$d %%",
    "error.network": "erreur réseau", "error.timeout": "délai dépassé",
    "error.noHTTP": "pas de réponse HTTP", "error.http": "HTTP %d",
    "error.parse": "réponse illisible",
    "error.unknownSource": "source inconnue", "error.noProvider": "aucun fournisseur",
    "error.unreachable": "réseau indisponible",
}

T["es"] = {
    "reset.days": "Se reinicia en %1$d d %2$d h",
    "reset.hours": "Se reinicia en %1$d h %2$d min",
    "reset.minutes": "Se reinicia en %d min",
    "reset.imminent": "Reiniciando ahora",
    "age.justNow": "ahora mismo",
    "age.seconds": "hace %d s", "age.minutes": "hace %d min",
    "age.hours": "hace %d h", "age.days": "hace %d d",
    "window.fiveHour": "Ventana de 5 h", "window.week": "Ventana semanal",
    "window.hours": "Ventana de %d h", "window.days": "Ventana de %d d",
    "window.generic": "Ventana de límite", "format.percent": "%d %%",
    "column.updating": "actualizando…", "column.stale": "datos de %@",
    "panel.updated": "Actualizado %@", "panel.noData": "Aún no hay datos",
    "panel.refresh.help": "Actualizar todas las columnas",
    "panel.empty.title": "Sin cuentas",
    "panel.empty.hint": "Clic derecho → «Añadir cuenta de Claude…» o «Añadir cuenta de Codex…»",
    "panel.hidden.title": "Todas las columnas ocultas",
    "panel.hidden.hint": "Clic derecho → «Mostrar columnas ocultas»",
    "menu.refresh": "Actualizar", "menu.addClaude": "Añadir cuenta de Claude…",
    "menu.addCodex": "Añadir cuenta de Codex…", "menu.hideColumn": "Ocultar columna",
    "menu.noColumns": "Sin columnas", "menu.showHidden": "Mostrar columnas ocultas",
    "menu.renameColumn": "Renombrar columna",
    "rename.title": "Nombre de la columna",
    "rename.hint": "Cómo se titula esta columna. Déjalo vacío para volver a «%@».",
    "common.save": "Guardar",
    "menu.hotKey": "Atajo: %@", "menu.hotKey.change": "Cambiar…",
    "menu.hotKey.standard": "Predeterminado (⌘P)", "menu.hotKey.disable": "Desactivar",
    "menu.loginItem": "Abrir al iniciar sesión", "menu.quit": "Salir",
    "hotkey.disabled": "desactivado", "hotkey.recorder.title": "Atajo",
    "hotkey.recorder.hint": "Pulsa una combinación — con ⌘, ⌥ o ⌃.",
    "hotkey.recorder.save": "Guardar",
    "hotkey.taken.title": "%@ ya está ocupado",
    "hotkey.taken.body": "Otra app ya lo usa. Tu ajuste anterior no ha cambiado.",
    "common.ok": "OK", "common.cancel": "Cancelar",
    "setup.claude.title": "Nueva cuenta de Claude",
    "setup.codex.title": "Nueva cuenta de Codex",
    "setup.profile.hint": "Elige un nombre corto para esta cuenta — por ejemplo work o personal. Será el título de la columna, y el CLI guardará ahí sus ajustes en una carpeta con ese nombre.",
    "setup.profile.terminal": "Tras pulsar «Crear» se abrirá el Terminal — inicia sesión allí.",
    "setup.profile.folder": "Carpeta: %@",
    "setup.profile.badChars": "Solo letras latinas, dígitos, guion y guion bajo.",
    "setup.profile.exists": "Ya existe un perfil con ese nombre.",
    "setup.create": "Crear", "setup.badName.title": "Nombre de perfil no válido",
    "setup.badName.body": "Solo letras latinas, dígitos, guion y guion bajo. El nombre no puede estar vacío ni repetido.",
    "setup.failed.title": "No se ha podido crear el perfil",
    "setup.missing.title": "No se ha encontrado %@",
    "setup.missing.body": "Instala el CLI e inténtalo de nuevo:\\n\\n%@",
    "setup.script.profile": "Perfil: %@",
    "setup.script.hint": "Inicia sesion y cierra esta ventana.",
    "loginItem.failed.title": "No se ha podido cambiar el inicio de sesión",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "error de red", "error.timeout": "tiempo agotado",
    "error.noHTTP": "sin respuesta HTTP", "error.http": "HTTP %d",
    "error.parse": "respuesta ilegible",
    "error.unknownSource": "origen desconocido", "error.noProvider": "sin proveedor",
    "error.unreachable": "red no disponible",
}

T["it"] = {
    "reset.days": "Reset tra %1$d g %2$d h",
    "reset.hours": "Reset tra %1$d h %2$d min",
    "reset.minutes": "Reset tra %d min",
    "reset.imminent": "Reset imminente",
    "age.justNow": "poco fa",
    "age.seconds": "%d s fa", "age.minutes": "%d min fa",
    "age.hours": "%d h fa", "age.days": "%d g fa",
    "window.fiveHour": "Finestra da 5 h", "window.week": "Finestra settimanale",
    "window.hours": "Finestra da %d h", "window.days": "Finestra da %d g",
    "window.generic": "Finestra di limite", "format.percent": "%d%%",
    "column.updating": "aggiornamento…", "column.stale": "dati di %@",
    "panel.updated": "Aggiornato %@", "panel.noData": "Ancora nessun dato",
    "panel.refresh.help": "Aggiorna tutte le colonne",
    "panel.empty.title": "Nessun account",
    "panel.empty.hint": "Clic destro → «Aggiungi account Claude…» o «Aggiungi account Codex…»",
    "panel.hidden.title": "Tutte le colonne nascoste",
    "panel.hidden.hint": "Clic destro → «Mostra colonne nascoste»",
    "menu.refresh": "Aggiorna", "menu.addClaude": "Aggiungi account Claude…",
    "menu.addCodex": "Aggiungi account Codex…", "menu.hideColumn": "Nascondi colonna",
    "menu.noColumns": "Nessuna colonna", "menu.showHidden": "Mostra colonne nascoste",
    "menu.renameColumn": "Rinomina colonna",
    "rename.title": "Nome della colonna",
    "rename.hint": "Come si chiama questa colonna. Lascia vuoto per tornare a «%@».",
    "common.save": "Salva",
    "menu.hotKey": "Scorciatoia: %@", "menu.hotKey.change": "Modifica…",
    "menu.hotKey.standard": "Predefinita (⌘P)", "menu.hotKey.disable": "Disattiva",
    "menu.loginItem": "Avvia all’accesso", "menu.quit": "Esci",
    "hotkey.disabled": "disattivata", "hotkey.recorder.title": "Scorciatoia",
    "hotkey.recorder.hint": "Premi una combinazione — con ⌘, ⌥ o ⌃.",
    "hotkey.recorder.save": "Salva",
    "hotkey.taken.title": "%@ è già in uso",
    "hotkey.taken.body": "Un’altra app lo usa già. L’impostazione precedente resta invariata.",
    "common.ok": "OK", "common.cancel": "Annulla",
    "setup.claude.title": "Nuovo account Claude",
    "setup.codex.title": "Nuovo account Codex",
    "setup.profile.hint": "Scegli un nome breve per questo account — per esempio work o personal. Diventerà il titolo della colonna e la CLI terrà le sue impostazioni in una cartella con quel nome.",
    "setup.profile.terminal": "Dopo «Crea» si apre il Terminale — accedi da lì.",
    "setup.profile.folder": "Cartella: %@",
    "setup.profile.badChars": "Solo lettere latine, cifre, trattino e trattino basso.",
    "setup.profile.exists": "Esiste già un profilo con questo nome.",
    "setup.create": "Crea", "setup.badName.title": "Nome profilo non valido",
    "setup.badName.body": "Solo lettere latine, cifre, trattino e trattino basso. Il nome non può essere vuoto o già usato.",
    "setup.failed.title": "Impossibile creare il profilo",
    "setup.missing.title": "Impossibile trovare %@",
    "setup.missing.body": "Installa la CLI e riprova:\\n\\n%@",
    "setup.script.profile": "Profilo: %@",
    "setup.script.hint": "Accedi, poi chiudi questa finestra.",
    "loginItem.failed.title": "Impossibile modificare l’avvio all’accesso",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "errore di rete", "error.timeout": "timeout",
    "error.noHTTP": "nessuna risposta HTTP", "error.http": "HTTP %d",
    "error.parse": "risposta non leggibile",
    "error.unknownSource": "origine sconosciuta", "error.noProvider": "nessun provider",
    "error.unreachable": "rete non disponibile",
}

T["pt-BR"] = {
    "reset.days": "Redefine em %1$d d %2$d h",
    "reset.hours": "Redefine em %1$d h %2$d min",
    "reset.minutes": "Redefine em %d min",
    "reset.imminent": "Redefinindo agora",
    "age.justNow": "agora mesmo",
    "age.seconds": "há %d s", "age.minutes": "há %d min",
    "age.hours": "há %d h", "age.days": "há %d d",
    "window.fiveHour": "Janela de 5 h", "window.week": "Janela semanal",
    "window.hours": "Janela de %d h", "window.days": "Janela de %d d",
    "window.generic": "Janela de limite", "format.percent": "%d%%",
    "column.updating": "atualizando…", "column.stale": "dados de %@",
    "panel.updated": "Atualizado %@", "panel.noData": "Ainda sem dados",
    "panel.refresh.help": "Atualizar todas as colunas",
    "panel.empty.title": "Sem contas",
    "panel.empty.hint": "Clique com o botão direito → “Adicionar conta Claude…” ou “Adicionar conta Codex…”",
    "panel.hidden.title": "Todas as colunas ocultas",
    "panel.hidden.hint": "Clique com o botão direito → “Mostrar colunas ocultas”",
    "menu.refresh": "Atualizar", "menu.addClaude": "Adicionar conta Claude…",
    "menu.addCodex": "Adicionar conta Codex…", "menu.hideColumn": "Ocultar coluna",
    "menu.noColumns": "Sem colunas", "menu.showHidden": "Mostrar colunas ocultas",
    "menu.renameColumn": "Renomear coluna",
    "rename.title": "Nome da coluna",
    "rename.hint": "Como esta coluna é rotulada. Deixe vazio para voltar a “%@”.",
    "common.save": "Salvar",
    "menu.hotKey": "Atalho: %@", "menu.hotKey.change": "Alterar…",
    "menu.hotKey.standard": "Padrão (⌘P)", "menu.hotKey.disable": "Desativar",
    "menu.loginItem": "Abrir ao iniciar sessão", "menu.quit": "Sair",
    "hotkey.disabled": "desativado", "hotkey.recorder.title": "Atalho",
    "hotkey.recorder.hint": "Pressione uma combinação — com ⌘, ⌥ ou ⌃.",
    "hotkey.recorder.save": "Salvar",
    "hotkey.taken.title": "%@ já está em uso",
    "hotkey.taken.body": "Outro app já usa esse atalho. Seu ajuste anterior foi mantido.",
    "common.ok": "OK", "common.cancel": "Cancelar",
    "setup.claude.title": "Nova conta Claude",
    "setup.codex.title": "Nova conta Codex",
    "setup.profile.hint": "Escolha um nome curto para esta conta — por exemplo work ou personal. Ele vira o título da coluna, e a CLI guarda as configurações numa pasta com esse nome.",
    "setup.profile.terminal": "Depois de “Criar”, o Terminal abre — faça login por lá.",
    "setup.profile.folder": "Pasta: %@",
    "setup.profile.badChars": "Apenas letras latinas, dígitos, hífen e sublinhado.",
    "setup.profile.exists": "Já existe um perfil com esse nome.",
    "setup.create": "Criar", "setup.badName.title": "Nome de perfil inválido",
    "setup.badName.body": "Apenas letras latinas, dígitos, hífen e sublinhado. O nome não pode estar vazio nem repetido.",
    "setup.failed.title": "Não foi possível criar o perfil",
    "setup.missing.title": "Não encontrei %@",
    "setup.missing.body": "Instale a CLI e tente de novo:\\n\\n%@",
    "setup.script.profile": "Perfil: %@",
    "setup.script.hint": "Faca login e feche esta janela.",
    "loginItem.failed.title": "Não foi possível mudar a abertura ao iniciar sessão",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "erro de rede", "error.timeout": "tempo esgotado",
    "error.noHTTP": "sem resposta HTTP", "error.http": "HTTP %d",
    "error.parse": "resposta ilegível",
    "error.unknownSource": "origem desconhecida", "error.noProvider": "sem provedor",
    "error.unreachable": "rede indisponível",
}

T["uk"] = {
    "reset.days": "Скидання через %1$d д %2$d год",
    "reset.hours": "Скидання через %1$d год %2$d хв",
    "reset.minutes": "Скидання через %d хв",
    "reset.imminent": "Скидання ось-ось",
    "age.justNow": "щойно",
    "age.seconds": "%d с тому", "age.minutes": "%d хв тому",
    "age.hours": "%d год тому", "age.days": "%d д тому",
    "window.fiveHour": "5-годинне вікно", "window.week": "Тижневе вікно",
    "window.hours": "%d-годинне вікно", "window.days": "%d-денне вікно",
    "window.generic": "Вікно ліміту", "format.percent": "%d %%",
    "column.updating": "оновлюю…", "column.stale": "дані %@",
    "panel.updated": "Оновлено %@", "panel.noData": "Даних ще немає",
    "panel.refresh.help": "Оновити всі колонки",
    "panel.empty.title": "Немає акаунтів",
    "panel.empty.hint": "Правий клік → «Додати акаунт Claude…» або «Додати акаунт Codex…»",
    "panel.hidden.title": "Усі колонки приховано",
    "panel.hidden.hint": "Правий клік → «Показати приховані колонки»",
    "menu.refresh": "Оновити", "menu.addClaude": "Додати акаунт Claude…",
    "menu.addCodex": "Додати акаунт Codex…", "menu.hideColumn": "Приховати колонку",
    "menu.noColumns": "Немає колонок", "menu.showHidden": "Показати приховані колонки",
    "menu.renameColumn": "Перейменувати колонку",
    "rename.title": "Назва колонки",
    "rename.hint": "Як підписати цю колонку. Порожньо — повернути «%@».",
    "common.save": "Зберегти",
    "menu.hotKey": "Гаряча клавіша: %@", "menu.hotKey.change": "Змінити…",
    "menu.hotKey.standard": "Стандартна (⌘P)", "menu.hotKey.disable": "Вимкнути",
    "menu.loginItem": "Запуск при вході", "menu.quit": "Вихід",
    "hotkey.disabled": "вимкнено", "hotkey.recorder.title": "Гаряча клавіша",
    "hotkey.recorder.hint": "Натисни комбінацію — обов’язково з ⌘, ⌥ або ⌃.",
    "hotkey.recorder.save": "Зберегти",
    "hotkey.taken.title": "Комбінація %@ зайнята",
    "hotkey.taken.body": "Її вже тримає інша програма. Попереднє налаштування лишилося без змін.",
    "common.ok": "Ок", "common.cancel": "Скасувати",
    "setup.claude.title": "Новий акаунт Claude",
    "setup.codex.title": "Новий акаунт Codex",
    "setup.profile.hint": "Придумай коротку назву для цього акаунта — наприклад work або personal. Вона стане заголовком колонки, а CLI триматиме налаштування в теці з такою назвою.",
    "setup.profile.terminal": "Після «Створити» відкриється Термінал — вхід робиться там.",
    "setup.profile.folder": "Тека: %@",
    "setup.profile.badChars": "Лише латиниця, цифри, дефіс і підкреслення.",
    "setup.profile.exists": "Профіль із такою назвою вже є.",
    "setup.create": "Створити", "setup.badName.title": "Погана назва профілю",
    "setup.badName.body": "Лише латиниця, цифри, дефіс і підкреслення. Назва не має бути порожньою або вже зайнятою.",
    "setup.failed.title": "Не вдалося створити профіль",
    "setup.missing.title": "Не знайшов %@",
    "setup.missing.body": "Встанови CLI і спробуй знову:\\n\\n%@",
    "setup.script.profile": "Профіль: %@",
    "setup.script.hint": "Увійди в акаунт, потім закрий це вікно.",
    "loginItem.failed.title": "Не вдалося змінити запуск при вході",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "збій мережі", "error.timeout": "тайм-аут",
    "error.noHTTP": "немає HTTP-відповіді", "error.http": "HTTP %d",
    "error.parse": "не розібрав відповідь",
    "error.unknownSource": "невідоме джерело", "error.noProvider": "немає провайдера",
    "error.unreachable": "мережа недоступна",
}

T["pl"] = {
    "reset.days": "Reset za %1$d d %2$d godz.",
    "reset.hours": "Reset za %1$d godz. %2$d min",
    "reset.minutes": "Reset za %d min",
    "reset.imminent": "Reset za chwilę",
    "age.justNow": "przed chwilą",
    "age.seconds": "%d s temu", "age.minutes": "%d min temu",
    "age.hours": "%d godz. temu", "age.days": "%d d temu",
    "window.fiveHour": "Okno 5-godzinne", "window.week": "Okno tygodniowe",
    "window.hours": "Okno %d-godzinne", "window.days": "Okno %d-dniowe",
    "window.generic": "Okno limitu", "format.percent": "%d%%",
    "column.updating": "odświeżam…", "column.stale": "dane z %@",
    "panel.updated": "Zaktualizowano %@", "panel.noData": "Jeszcze brak danych",
    "panel.refresh.help": "Odśwież wszystkie kolumny",
    "panel.empty.title": "Brak kont",
    "panel.empty.hint": "Prawy przycisk → „Dodaj konto Claude…” lub „Dodaj konto Codex…”",
    "panel.hidden.title": "Wszystkie kolumny ukryte",
    "panel.hidden.hint": "Prawy przycisk → „Pokaż ukryte kolumny”",
    "menu.refresh": "Odśwież", "menu.addClaude": "Dodaj konto Claude…",
    "menu.addCodex": "Dodaj konto Codex…", "menu.hideColumn": "Ukryj kolumnę",
    "menu.noColumns": "Brak kolumn", "menu.showHidden": "Pokaż ukryte kolumny",
    "menu.renameColumn": "Zmień nazwę kolumny",
    "rename.title": "Nazwa kolumny",
    "rename.hint": "Jak podpisać tę kolumnę. Puste — wróć do „%@”.",
    "common.save": "Zapisz",
    "menu.hotKey": "Skrót: %@", "menu.hotKey.change": "Zmień…",
    "menu.hotKey.standard": "Domyślny (⌘P)", "menu.hotKey.disable": "Wyłącz",
    "menu.loginItem": "Uruchamiaj przy logowaniu", "menu.quit": "Zakończ",
    "hotkey.disabled": "wyłączony", "hotkey.recorder.title": "Skrót",
    "hotkey.recorder.hint": "Naciśnij kombinację — z ⌘, ⌥ lub ⌃.",
    "hotkey.recorder.save": "Zapisz",
    "hotkey.taken.title": "%@ jest już zajęty",
    "hotkey.taken.body": "Inna aplikacja już go używa. Poprzednie ustawienie pozostało bez zmian.",
    "common.ok": "OK", "common.cancel": "Anuluj",
    "setup.claude.title": "Nowe konto Claude",
    "setup.codex.title": "Nowe konto Codex",
    "setup.profile.hint": "Wybierz krótką nazwę dla tego konta — na przykład work albo personal. Stanie się nagłówkiem kolumny, a CLI będzie trzymać ustawienia w folderze o tej nazwie.",
    "setup.profile.terminal": "Po kliknięciu „Utwórz” otworzy się Terminal — zaloguj się tam.",
    "setup.profile.folder": "Folder: %@",
    "setup.profile.badChars": "Tylko litery łacińskie, cyfry, myślnik i podkreślenie.",
    "setup.profile.exists": "Profil o tej nazwie już istnieje.",
    "setup.create": "Utwórz", "setup.badName.title": "Zła nazwa profilu",
    "setup.badName.body": "Tylko litery łacińskie, cyfry, myślnik i podkreślenie. Nazwa nie może być pusta ani zajęta.",
    "setup.failed.title": "Nie udało się utworzyć profilu",
    "setup.missing.title": "Nie znaleziono %@",
    "setup.missing.body": "Zainstaluj CLI i spróbuj ponownie:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Zaloguj sie, potem zamknij to okno.",
    "loginItem.failed.title": "Nie udało się zmienić uruchamiania przy logowaniu",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "błąd sieci", "error.timeout": "przekroczono czas",
    "error.noHTTP": "brak odpowiedzi HTTP", "error.http": "HTTP %d",
    "error.parse": "nieczytelna odpowiedź",
    "error.unknownSource": "nieznane źródło", "error.noProvider": "brak dostawcy",
    "error.unreachable": "sieć niedostępna",
}

T["tr"] = {
    "reset.days": "%1$d g %2$d sa sonra sıfırlanır",
    "reset.hours": "%1$d sa %2$d dk sonra sıfırlanır",
    "reset.minutes": "%d dk sonra sıfırlanır",
    "reset.imminent": "Şimdi sıfırlanıyor",
    "age.justNow": "az önce",
    "age.seconds": "%d sn önce", "age.minutes": "%d dk önce",
    "age.hours": "%d sa önce", "age.days": "%d g önce",
    "window.fiveHour": "5 saatlik pencere", "window.week": "Haftalık pencere",
    "window.hours": "%d saatlik pencere", "window.days": "%d günlük pencere",
    "window.generic": "Limit penceresi", "format.percent": "%%%d",
    "column.updating": "yenileniyor…", "column.stale": "%@ verisi",
    "panel.updated": "Güncellendi %@", "panel.noData": "Henüz veri yok",
    "panel.refresh.help": "Tüm sütunları yenile",
    "panel.empty.title": "Hesap yok",
    "panel.empty.hint": "Sağ tık → “Claude hesabı ekle…” ya da “Codex hesabı ekle…”",
    "panel.hidden.title": "Tüm sütunlar gizli",
    "panel.hidden.hint": "Sağ tık → “Gizli sütunları göster”",
    "menu.refresh": "Yenile", "menu.addClaude": "Claude hesabı ekle…",
    "menu.addCodex": "Codex hesabı ekle…", "menu.hideColumn": "Sütunu gizle",
    "menu.noColumns": "Sütun yok", "menu.showHidden": "Gizli sütunları göster",
    "menu.renameColumn": "Sütunu yeniden adlandır",
    "rename.title": "Sütun adı",
    "rename.hint": "Bu sütunun etiketi. Boş bırakırsan “%@” geri gelir.",
    "common.save": "Kaydet",
    "menu.hotKey": "Kısayol: %@", "menu.hotKey.change": "Değiştir…",
    "menu.hotKey.standard": "Varsayılan (⌘P)", "menu.hotKey.disable": "Kapat",
    "menu.loginItem": "Girişte başlat", "menu.quit": "Çık",
    "hotkey.disabled": "kapalı", "hotkey.recorder.title": "Kısayol",
    "hotkey.recorder.hint": "Bir kombinasyona bas — ⌘, ⌥ ya da ⌃ içermeli.",
    "hotkey.recorder.save": "Kaydet",
    "hotkey.taken.title": "%@ zaten kullanılıyor",
    "hotkey.taken.body": "Başka bir uygulama onu tutuyor. Önceki ayarın değişmedi.",
    "common.ok": "Tamam", "common.cancel": "Vazgeç",
    "setup.claude.title": "Yeni Claude hesabı",
    "setup.codex.title": "Yeni Codex hesabı",
    "setup.profile.hint": "Bu hesap için kısa bir ad seç — örneğin work ya da personal. Sütun başlığı olacak ve CLI ayarlarını bu adı taşıyan klasörde tutacak.",
    "setup.profile.terminal": "“Oluştur”dan sonra Terminal açılır — girişi orada yap.",
    "setup.profile.folder": "Klasör: %@",
    "setup.profile.badChars": "Yalnızca Latin harfleri, rakam, tire ve alt çizgi.",
    "setup.profile.exists": "Bu adda bir profil zaten var.",
    "setup.create": "Oluştur", "setup.badName.title": "Geçersiz profil adı",
    "setup.badName.body": "Yalnızca Latin harfleri, rakam, tire ve alt çizgi. Ad boş ya da kullanımda olamaz.",
    "setup.failed.title": "Profil oluşturulamadı",
    "setup.missing.title": "%@ bulunamadı",
    "setup.missing.body": "CLI’yi kur ve tekrar dene:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Giris yap, sonra bu pencereyi kapat.",
    "loginItem.failed.title": "Girişte başlatma değiştirilemedi",
    "notification.title": "%1$@ — %%%2$d", "notification.body": "%1$@: %%%2$d",
    "error.network": "ağ hatası", "error.timeout": "zaman aşımı",
    "error.noHTTP": "HTTP yanıtı yok", "error.http": "HTTP %d",
    "error.parse": "yanıt çözümlenemedi",
    "error.unknownSource": "bilinmeyen kaynak", "error.noProvider": "sağlayıcı yok",
    "error.unreachable": "ağ kullanılamıyor",
}

T["ja"] = {
    "reset.days": "リセットまで %1$d日 %2$d時間",
    "reset.hours": "リセットまで %1$d時間 %2$d分",
    "reset.minutes": "リセットまで %d分",
    "reset.imminent": "まもなくリセット",
    "age.justNow": "たった今",
    "age.seconds": "%d秒前", "age.minutes": "%d分前",
    "age.hours": "%d時間前", "age.days": "%d日前",
    "window.fiveHour": "5時間ウィンドウ", "window.week": "週間ウィンドウ",
    "window.hours": "%d時間ウィンドウ", "window.days": "%d日ウィンドウ",
    "window.generic": "制限ウィンドウ", "format.percent": "%d%%",
    "column.updating": "更新中…", "column.stale": "%@のデータ",
    "panel.updated": "更新 %@", "panel.noData": "データがまだありません",
    "panel.refresh.help": "すべての列を更新",
    "panel.empty.title": "アカウントなし",
    "panel.empty.hint": "右クリック →「Claude アカウントを追加…」または「Codex アカウントを追加…」",
    "panel.hidden.title": "すべての列が非表示",
    "panel.hidden.hint": "右クリック →「非表示の列を表示」",
    "menu.refresh": "更新", "menu.addClaude": "Claude アカウントを追加…",
    "menu.addCodex": "Codex アカウントを追加…", "menu.hideColumn": "列を非表示",
    "menu.noColumns": "列がありません", "menu.showHidden": "非表示の列を表示",
    "menu.renameColumn": "列の名前を変更",
    "rename.title": "列の名前",
    "rename.hint": "この列の見出しです。空にすると「%@」に戻ります。",
    "common.save": "保存",
    "menu.hotKey": "ショートカット: %@", "menu.hotKey.change": "変更…",
    "menu.hotKey.standard": "デフォルト (⌘P)", "menu.hotKey.disable": "オフにする",
    "menu.loginItem": "ログイン時に起動", "menu.quit": "終了",
    "hotkey.disabled": "オフ", "hotkey.recorder.title": "ショートカット",
    "hotkey.recorder.hint": "組み合わせを押してください — ⌘、⌥、⌃ のいずれかが必要です。",
    "hotkey.recorder.save": "保存",
    "hotkey.taken.title": "%@ は使用中です",
    "hotkey.taken.body": "他のアプリが使っています。以前の設定のままです。",
    "common.ok": "OK", "common.cancel": "キャンセル",
    "setup.claude.title": "新しい Claude アカウント",
    "setup.codex.title": "新しい Codex アカウント",
    "setup.profile.hint": "このアカウントの短い名前を決めてください（例: work、personal）。列の見出しになり、CLI はその名前のフォルダに設定を保存します。",
    "setup.profile.terminal": "「作成」を押すとターミナルが開きます。ログインはそこで行います。",
    "setup.profile.folder": "フォルダ: %@",
    "setup.profile.badChars": "半角英字・数字・ハイフン・アンダースコアのみ。",
    "setup.profile.exists": "同じ名前のプロファイルがすでにあります。",
    "setup.create": "作成", "setup.badName.title": "プロファイル名が不正です",
    "setup.badName.body": "半角英字・数字・ハイフン・アンダースコアのみ。空や既存の名前は使えません。",
    "setup.failed.title": "プロファイルを作成できませんでした",
    "setup.missing.title": "%@ が見つかりません",
    "setup.missing.body": "CLI をインストールして再試行してください:\\n\\n%@",
    "setup.script.profile": "プロファイル: %@",
    "setup.script.hint": "ログインしたら、このウインドウを閉じてください。",
    "loginItem.failed.title": "ログイン時の起動を変更できませんでした",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "ネットワークエラー", "error.timeout": "タイムアウト",
    "error.noHTTP": "HTTP 応答なし", "error.http": "HTTP %d",
    "error.parse": "応答を解析できません",
    "error.unknownSource": "不明なソース", "error.noProvider": "プロバイダなし",
    "error.unreachable": "ネットワークに接続できません",
}

T["ko"] = {
    "reset.days": "%1$d일 %2$d시간 후 초기화",
    "reset.hours": "%1$d시간 %2$d분 후 초기화",
    "reset.minutes": "%d분 후 초기화",
    "reset.imminent": "곧 초기화",
    "age.justNow": "방금",
    "age.seconds": "%d초 전", "age.minutes": "%d분 전",
    "age.hours": "%d시간 전", "age.days": "%d일 전",
    "window.fiveHour": "5시간 창", "window.week": "주간 창",
    "window.hours": "%d시간 창", "window.days": "%d일 창",
    "window.generic": "한도 창", "format.percent": "%d%%",
    "column.updating": "새로고침 중…", "column.stale": "%@ 데이터",
    "panel.updated": "업데이트 %@", "panel.noData": "아직 데이터 없음",
    "panel.refresh.help": "모든 열 새로고침",
    "panel.empty.title": "계정 없음",
    "panel.empty.hint": "오른쪽 클릭 → ‘Claude 계정 추가…’ 또는 ‘Codex 계정 추가…’",
    "panel.hidden.title": "모든 열 숨김",
    "panel.hidden.hint": "오른쪽 클릭 → ‘숨긴 열 보기’",
    "menu.refresh": "새로고침", "menu.addClaude": "Claude 계정 추가…",
    "menu.addCodex": "Codex 계정 추가…", "menu.hideColumn": "열 숨기기",
    "menu.noColumns": "열 없음", "menu.showHidden": "숨긴 열 보기",
    "menu.renameColumn": "열 이름 변경",
    "rename.title": "열 이름",
    "rename.hint": "이 열의 제목입니다. 비우면 ‘%@’ 로 돌아갑니다.",
    "common.save": "저장",
    "menu.hotKey": "단축키: %@", "menu.hotKey.change": "변경…",
    "menu.hotKey.standard": "기본값 (⌘P)", "menu.hotKey.disable": "끄기",
    "menu.loginItem": "로그인 시 실행", "menu.quit": "종료",
    "hotkey.disabled": "꺼짐", "hotkey.recorder.title": "단축키",
    "hotkey.recorder.hint": "조합을 누르세요 — ⌘, ⌥ 또는 ⌃ 가 필요합니다.",
    "hotkey.recorder.save": "저장",
    "hotkey.taken.title": "%@ 은(는) 이미 사용 중입니다",
    "hotkey.taken.body": "다른 앱이 사용 중입니다. 이전 설정이 그대로 유지됩니다.",
    "common.ok": "확인", "common.cancel": "취소",
    "setup.claude.title": "새 Claude 계정",
    "setup.codex.title": "새 Codex 계정",
    "setup.profile.hint": "이 계정의 짧은 이름을 정하세요 — 예를 들어 work 또는 personal. 열 제목이 되고, CLI 는 그 이름의 폴더에 설정을 저장합니다.",
    "setup.profile.terminal": "‘생성’을 누르면 터미널이 열립니다. 로그인은 거기서 하세요.",
    "setup.profile.folder": "폴더: %@",
    "setup.profile.badChars": "영문자, 숫자, 하이픈, 밑줄만 가능합니다.",
    "setup.profile.exists": "같은 이름의 프로파일이 이미 있습니다.",
    "setup.create": "생성", "setup.badName.title": "잘못된 프로파일 이름",
    "setup.badName.body": "영문자, 숫자, 하이픈, 밑줄만 가능합니다. 비어 있거나 이미 사용 중이면 안 됩니다.",
    "setup.failed.title": "프로파일을 만들지 못했습니다",
    "setup.missing.title": "%@ 을(를) 찾지 못했습니다",
    "setup.missing.body": "CLI 를 설치하고 다시 시도하세요:\\n\\n%@",
    "setup.script.profile": "프로파일: %@",
    "setup.script.hint": "로그인한 다음 이 창을 닫으세요.",
    "loginItem.failed.title": "로그인 시 실행을 변경하지 못했습니다",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "네트워크 오류", "error.timeout": "시간 초과",
    "error.noHTTP": "HTTP 응답 없음", "error.http": "HTTP %d",
    "error.parse": "응답을 해석할 수 없음",
    "error.unknownSource": "알 수 없는 소스", "error.noProvider": "제공자 없음",
    "error.unreachable": "네트워크 사용 불가",
}

T["zh-Hans"] = {
    "reset.days": "%1$d 天 %2$d 小时后重置",
    "reset.hours": "%1$d 小时 %2$d 分钟后重置",
    "reset.minutes": "%d 分钟后重置",
    "reset.imminent": "即将重置",
    "age.justNow": "刚刚",
    "age.seconds": "%d 秒前", "age.minutes": "%d 分钟前",
    "age.hours": "%d 小时前", "age.days": "%d 天前",
    "window.fiveHour": "5 小时窗口", "window.week": "每周窗口",
    "window.hours": "%d 小时窗口", "window.days": "%d 天窗口",
    "window.generic": "限额窗口", "format.percent": "%d%%",
    "column.updating": "正在刷新…", "column.stale": "%@的数据",
    "panel.updated": "更新于 %@", "panel.noData": "暂无数据",
    "panel.refresh.help": "刷新所有列",
    "panel.empty.title": "没有账户",
    "panel.empty.hint": "右键点击 →「添加 Claude 账户…」或「添加 Codex 账户…」",
    "panel.hidden.title": "所有列已隐藏",
    "panel.hidden.hint": "右键点击 →「显示隐藏的列」",
    "menu.refresh": "刷新", "menu.addClaude": "添加 Claude 账户…",
    "menu.addCodex": "添加 Codex 账户…", "menu.hideColumn": "隐藏列",
    "menu.noColumns": "没有列", "menu.showHidden": "显示隐藏的列",
    "menu.renameColumn": "重命名列",
    "rename.title": "列名称",
    "rename.hint": "这一列的标题。留空则恢复为「%@」。",
    "common.save": "存储",
    "menu.hotKey": "快捷键：%@", "menu.hotKey.change": "更改…",
    "menu.hotKey.standard": "默认 (⌘P)", "menu.hotKey.disable": "关闭",
    "menu.loginItem": "登录时启动", "menu.quit": "退出",
    "hotkey.disabled": "已关闭", "hotkey.recorder.title": "快捷键",
    "hotkey.recorder.hint": "按下组合键 — 必须包含 ⌘、⌥ 或 ⌃。",
    "hotkey.recorder.save": "存储",
    "hotkey.taken.title": "%@ 已被占用",
    "hotkey.taken.body": "另一个 App 已占用它。之前的设置保持不变。",
    "common.ok": "好", "common.cancel": "取消",
    "setup.claude.title": "新的 Claude 账户",
    "setup.codex.title": "新的 Codex 账户",
    "setup.profile.hint": "为这个账户取一个简短的名字，例如 work 或 personal。它会成为列标题，CLI 也会把设置放在同名文件夹里。",
    "setup.profile.terminal": "点击「创建」后会打开「终端」，在那里登录。",
    "setup.profile.folder": "文件夹：%@",
    "setup.profile.badChars": "只能使用拉丁字母、数字、连字符和下划线。",
    "setup.profile.exists": "同名的配置已存在。",
    "setup.create": "创建", "setup.badName.title": "配置名称无效",
    "setup.badName.body": "只能使用拉丁字母、数字、连字符和下划线。名称不能为空或重复。",
    "setup.failed.title": "无法创建配置",
    "setup.missing.title": "找不到 %@",
    "setup.missing.body": "请安装 CLI 后重试：\\n\\n%@",
    "setup.script.profile": "配置：%@",
    "setup.script.hint": "登录后关闭此窗口。",
    "loginItem.failed.title": "无法更改登录时启动",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@：%2$d%%",
    "error.network": "网络错误", "error.timeout": "超时",
    "error.noHTTP": "没有 HTTP 响应", "error.http": "HTTP %d",
    "error.parse": "无法解析响应",
    "error.unknownSource": "来源未知", "error.noProvider": "没有提供方",
    "error.unreachable": "网络不可用",
}

T["zh-Hant"] = {
    "reset.days": "%1$d 天 %2$d 小時後重置",
    "reset.hours": "%1$d 小時 %2$d 分鐘後重置",
    "reset.minutes": "%d 分鐘後重置",
    "reset.imminent": "即將重置",
    "age.justNow": "剛剛",
    "age.seconds": "%d 秒前", "age.minutes": "%d 分鐘前",
    "age.hours": "%d 小時前", "age.days": "%d 天前",
    "window.fiveHour": "5 小時視窗", "window.week": "每週視窗",
    "window.hours": "%d 小時視窗", "window.days": "%d 天視窗",
    "window.generic": "限額視窗", "format.percent": "%d%%",
    "column.updating": "更新中…", "column.stale": "%@的資料",
    "panel.updated": "更新於 %@", "panel.noData": "尚無資料",
    "panel.refresh.help": "重新整理所有欄",
    "panel.empty.title": "沒有帳號",
    "panel.empty.hint": "右鍵點按 →「加入 Claude 帳號…」或「加入 Codex 帳號…」",
    "panel.hidden.title": "所有欄皆已隱藏",
    "panel.hidden.hint": "右鍵點按 →「顯示隱藏的欄」",
    "menu.refresh": "重新整理", "menu.addClaude": "加入 Claude 帳號…",
    "menu.addCodex": "加入 Codex 帳號…", "menu.hideColumn": "隱藏欄",
    "menu.noColumns": "沒有欄", "menu.showHidden": "顯示隱藏的欄",
    "menu.renameColumn": "重新命名欄",
    "rename.title": "欄名稱",
    "rename.hint": "這一欄的標題。留空則恢復為「%@」。",
    "common.save": "儲存",
    "menu.hotKey": "快速鍵：%@", "menu.hotKey.change": "更改…",
    "menu.hotKey.standard": "預設 (⌘P)", "menu.hotKey.disable": "關閉",
    "menu.loginItem": "登入時啟動", "menu.quit": "結束",
    "hotkey.disabled": "已關閉", "hotkey.recorder.title": "快速鍵",
    "hotkey.recorder.hint": "按下組合鍵 — 必須包含 ⌘、⌥ 或 ⌃。",
    "hotkey.recorder.save": "儲存",
    "hotkey.taken.title": "%@ 已被佔用",
    "hotkey.taken.body": "另一個 App 已佔用它。先前的設定保持不變。",
    "common.ok": "好", "common.cancel": "取消",
    "setup.claude.title": "新的 Claude 帳號",
    "setup.codex.title": "新的 Codex 帳號",
    "setup.profile.hint": "為這個帳號取一個簡短的名稱，例如 work 或 personal。它會成為欄標題，CLI 也會把設定放在同名檔案夾裡。",
    "setup.profile.terminal": "點按「製作」後會開啟「終端機」，請在那裡登入。",
    "setup.profile.folder": "檔案夾：%@",
    "setup.profile.badChars": "僅能使用拉丁字母、數字、連字號和底線。",
    "setup.profile.exists": "同名的設定檔已存在。",
    "setup.create": "製作", "setup.badName.title": "設定檔名稱無效",
    "setup.badName.body": "僅能使用拉丁字母、數字、連字號和底線。名稱不能空白或重複。",
    "setup.failed.title": "無法製作設定檔",
    "setup.missing.title": "找不到 %@",
    "setup.missing.body": "請安裝 CLI 後再試一次：\\n\\n%@",
    "setup.script.profile": "設定檔：%@",
    "setup.script.hint": "登入後請關閉此視窗。",
    "loginItem.failed.title": "無法更改登入時啟動",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@：%2$d%%",
    "error.network": "網路錯誤", "error.timeout": "逾時",
    "error.noHTTP": "沒有 HTTP 回應", "error.http": "HTTP %d",
    "error.parse": "無法解析回應",
    "error.unknownSource": "來源不明", "error.noProvider": "沒有提供者",
    "error.unreachable": "網路無法使用",
}


# Уведомления о сбросе окна. Держим отдельным словарём: строки notification.*
# у многих языков совпадают дословно, и точечная правка каждой таблицы была бы
# неоднозначной. Оба ключа несут ровно один «%@» — спецификаторы совпадают везде.
_RESET = {
    "en":      ("%@ — limit reset",          "%@ is available again"),
    "ru":      ("%@ — лимит сброшен",         "%@ снова доступно"),
    "de":      ("%@ — Limit zurückgesetzt",   "%@ ist wieder verfügbar"),
    "fr":      ("%@ — limite réinitialisée",  "%@ est de nouveau disponible"),
    "es":      ("%@ — límite reiniciado",     "%@ vuelve a estar disponible"),
    "it":      ("%@ — limite azzerato",       "%@ è di nuovo disponibile"),
    "pt-BR":   ("%@ — limite redefinido",     "%@ está disponível de novo"),
    "uk":      ("%@ — ліміт скинуто",         "%@ знову доступне"),
    "pl":      ("%@ — limit zresetowany",     "%@ znów dostępne"),
    "tr":      ("%@ — limit sıfırlandı",      "%@ yeniden kullanılabilir"),
    "ja":      ("%@ — 制限リセット",           "%@ が再び利用可能です"),
    "ko":      ("%@ — 한도 초기화",            "%@ 다시 사용 가능"),
    "zh-Hans": ("%@ — 限额已重置",            "%@ 重新可用"),
    "zh-Hant": ("%@ — 限額已重置",            "%@ 重新可用"),
}
for _lang, (_title, _body) in _RESET.items():
    T[_lang]["notification.reset.title"] = _title
    T[_lang]["notification.reset.body"] = _body


# Строки статистики под окнами. Без спецификаторов — подставляется только
# готовое число, поэтому проверка форматов их не касается.
_STATS = {
    "en":      ("Credits", "unlimited", "Early resets", "Extra usage"),
    "ru":      ("Кредиты", "без лимита", "Досрочные сбросы", "Расход сверх лимита"),
    "de":      ("Guthaben", "unbegrenzt", "Vorzeitige Resets", "Zusatzverbrauch"),
    "fr":      ("Crédits", "illimité", "Réinit. anticipées", "Usage supplémentaire"),
    "es":      ("Créditos", "ilimitado", "Reinicios anticipados", "Uso adicional"),
    "it":      ("Crediti", "illimitato", "Reset anticipati", "Uso aggiuntivo"),
    "pt-BR":   ("Créditos", "ilimitado", "Redefinições antecipadas", "Uso adicional"),
    "uk":      ("Кредити", "без ліміту", "Дострокові скидання", "Витрати понад ліміт"),
    "pl":      ("Kredyty", "bez limitu", "Wcześniejsze resety", "Zużycie ponad limit"),
    "tr":      ("Krediler", "sınırsız", "Erken sıfırlamalar", "Ek kullanım"),
    "ja":      ("クレジット", "無制限", "早期リセット", "追加利用"),
    "ko":      ("크레딧", "무제한", "조기 초기화", "추가 사용"),
    "zh-Hans": ("额度", "无限制", "提前重置", "额外用量"),
    "zh-Hant": ("額度", "無限制", "提前重置", "額外用量"),
}
for _lang, (_credits, _unlimited, _resets, _extra) in _STATS.items():
    T[_lang]["stat.credits"] = _credits
    T[_lang]["stat.unlimited"] = _unlimited
    T[_lang]["stat.resetCredits"] = _resets
    T[_lang]["stat.extraUsage"] = _extra


# Прогноз исчерпания: «упрёшься в 100 % примерно тогда-то». Один «%@» —
# готовая строка времени (Format.resetAbsolute), спецификатор совпадает везде.
_BURN = {
    "en":      "full ≈ %@",
    "ru":      "предел ≈ %@",
    "de":      "voll ≈ %@",
    "fr":      "plein ≈ %@",
    "es":      "lleno ≈ %@",
    "it":      "pieno ≈ %@",
    "pt-BR":   "cheio ≈ %@",
    "uk":      "межа ≈ %@",
    "pl":      "limit ≈ %@",
    "tr":      "dolum ≈ %@",
    "ja":      "上限 ≈ %@",
    "ko":      "한도 ≈ %@",
    "zh-Hans": "上限 ≈ %@",
    "zh-Hant": "上限 ≈ %@",
}
for _lang, _text in _BURN.items():
    T[_lang]["burn.limitAt"] = _text


# Удаление аккаунта. menu.removeColumn кладём в общий блок меню отдельно ниже,
# здесь — подтверждение. remove.title несёт один «%@» (заголовок колонки).
_REMOVE = {
    "en":      ("Remove account",   "Remove %@?",
                "The account's credentials will be deleted permanently. Sign in again with claude or codex to bring it back.",
                "Delete", "Couldn't remove the account"),
    "ru":      ("Удалить аккаунт",   "Удалить %@?",
                "Учётные данные аккаунта будут удалены без возможности отмены. Чтобы вернуть его, войдите заново через claude или codex.",
                "Удалить", "Не удалось удалить аккаунт"),
    "de":      ("Konto entfernen",   "%@ entfernen?",
                "Die Zugangsdaten des Kontos werden endgültig gelöscht. Melde dich mit claude oder codex erneut an, um es zurückzuholen.",
                "Löschen", "Konto konnte nicht entfernt werden"),
    "fr":      ("Supprimer le compte", "Supprimer %@ ?",
                "Les identifiants du compte seront supprimés définitivement. Reconnecte-toi avec claude ou codex pour le récupérer.",
                "Supprimer", "Impossible de supprimer le compte"),
    "es":      ("Eliminar cuenta",   "¿Eliminar %@?",
                "Las credenciales de la cuenta se eliminarán de forma permanente. Vuelve a iniciar sesión con claude o codex para recuperarla.",
                "Eliminar", "No se pudo eliminar la cuenta"),
    "it":      ("Rimuovi account",   "Rimuovere %@?",
                "Le credenziali dell'account verranno eliminate definitivamente. Accedi di nuovo con claude o codex per ripristinarlo.",
                "Elimina", "Impossibile rimuovere l'account"),
    "pt-BR":   ("Remover conta",     "Remover %@?",
                "As credenciais da conta serão excluídas permanentemente. Entre novamente com claude ou codex para recuperá-la.",
                "Excluir", "Não foi possível remover a conta"),
    "uk":      ("Видалити акаунт",   "Видалити %@?",
                "Облікові дані акаунта буде видалено безповоротно. Щоб повернути його, увійдіть знову через claude або codex.",
                "Видалити", "Не вдалося видалити акаунт"),
    "pl":      ("Usuń konto",        "Usunąć %@?",
                "Dane logowania konta zostaną trwale usunięte. Zaloguj się ponownie przez claude lub codex, aby je przywrócić.",
                "Usuń", "Nie udało się usunąć konta"),
    "tr":      ("Hesabı kaldır",     "%@ kaldırılsın mı?",
                "Hesabın kimlik bilgileri kalıcı olarak silinecek. Geri getirmek için claude veya codex ile yeniden giriş yap.",
                "Sil", "Hesap kaldırılamadı"),
    "ja":      ("アカウントを削除",   "%@ を削除しますか？",
                "アカウントの認証情報は完全に削除されます。元に戻すには claude か codex で再度サインインしてください。",
                "削除", "アカウントを削除できませんでした"),
    "ko":      ("계정 삭제",          "%@ 삭제할까요?",
                "계정 자격 증명이 영구적으로 삭제됩니다. 되돌리려면 claude 또는 codex로 다시 로그인하세요.",
                "삭제", "계정을 삭제하지 못했습니다"),
    "zh-Hans": ("移除账号",          "移除 %@？",
                "该账号的登录凭据将被永久删除。用 claude 或 codex 重新登录即可恢复。",
                "删除", "无法移除账号"),
    "zh-Hant": ("移除帳號",          "移除 %@？",
                "該帳號的登入憑證將被永久刪除。用 claude 或 codex 重新登入即可復原。",
                "刪除", "無法移除帳號"),
}
for _lang, (_menu, _title, _body, _delete, _failed) in _REMOVE.items():
    T[_lang]["menu.removeColumn"] = _menu
    T[_lang]["remove.title"] = _title
    T[_lang]["remove.body"] = _body
    T[_lang]["remove.delete"] = _delete
    T[_lang]["remove.failed.title"] = _failed


# Проверка обновлений. update.available и update.upToDate несут один «%@»
# (номер версии), остальные — без подстановок.
_UPDATE = {
    "en":      ("Check for updates", "Version %@ is available", "Open the release page to download it.",
                "Open release", "You're on the latest version (%@)", "Couldn't check for updates"),
    "ru":      ("Проверить наличие обновлений", "Доступна версия %@", "Откройте страницу релиза, чтобы скачать.",
                "Открыть релиз", "Установлена последняя версия (%@)", "Не удалось проверить обновления"),
    "de":      ("Nach Updates suchen", "Version %@ ist verfügbar", "Öffne die Release-Seite zum Download.",
                "Release öffnen", "Du hast die neueste Version (%@)", "Update-Prüfung fehlgeschlagen"),
    "fr":      ("Rechercher des mises à jour", "La version %@ est disponible", "Ouvre la page de release pour la télécharger.",
                "Ouvrir la release", "Tu as la dernière version (%@)", "Échec de la vérification des mises à jour"),
    "es":      ("Buscar actualizaciones", "La versión %@ está disponible", "Abre la página de la versión para descargarla.",
                "Abrir versión", "Tienes la última versión (%@)", "No se pudo buscar actualizaciones"),
    "it":      ("Cerca aggiornamenti", "La versione %@ è disponibile", "Apri la pagina della release per scaricarla.",
                "Apri release", "Hai l'ultima versione (%@)", "Impossibile cercare aggiornamenti"),
    "pt-BR":   ("Procurar atualizações", "A versão %@ está disponível", "Abra a página da versão para baixar.",
                "Abrir versão", "Você está na versão mais recente (%@)", "Não foi possível procurar atualizações"),
    "uk":      ("Перевірити оновлення", "Доступна версія %@", "Відкрийте сторінку релізу, щоб завантажити.",
                "Відкрити реліз", "Встановлено найновішу версію (%@)", "Не вдалося перевірити оновлення"),
    "pl":      ("Sprawdź aktualizacje", "Dostępna jest wersja %@", "Otwórz stronę wydania, aby pobrać.",
                "Otwórz wydanie", "Masz najnowszą wersję (%@)", "Nie udało się sprawdzić aktualizacji"),
    "tr":      ("Güncellemeleri denetle", "%@ sürümü mevcut", "İndirmek için sürüm sayfasını aç.",
                "Sürümü aç", "En son sürümü kullanıyorsun (%@)", "Güncellemeler denetlenemedi"),
    "ja":      ("アップデートを確認", "バージョン %@ が利用可能です", "リリースページを開いてダウンロードしてください。",
                "リリースを開く", "最新バージョンです (%@)", "アップデートを確認できませんでした"),
    "ko":      ("업데이트 확인", "버전 %@ 사용 가능", "다운로드하려면 릴리스 페이지를 여세요.",
                "릴리스 열기", "최신 버전입니다 (%@)", "업데이트를 확인하지 못했습니다"),
    "zh-Hans": ("检查更新", "有新版本 %@", "打开发布页面即可下载。",
                "打开发布页", "已是最新版本 (%@)", "无法检查更新"),
    "zh-Hant": ("檢查更新", "有新版本 %@", "開啟發布頁面即可下載。",
                "開啟發布頁", "已是最新版本 (%@)", "無法檢查更新"),
}
for _lang, (_menu, _avail, _availBody, _open, _upToDate, _failed) in _UPDATE.items():
    # Многоточие — действие ведёт к проверке/диалогу, а не выполняется сразу.
    T[_lang]["menu.checkUpdates"] = _menu + "…"
    T[_lang]["update.available"] = _avail
    T[_lang]["update.availableBody"] = _availBody
    T[_lang]["update.open"] = _open
    T[_lang]["update.upToDate"] = _upToDate
    T[_lang]["update.failed"] = _failed


# Установка обновления в один клик. Без спецификаторов.
_INSTALL = {
    "en":      ("Update now", "Downloading the update…", "Couldn't install the update",
                "The release has no downloadable build.", "Download failed.",
                "Checksum didn't match — download not trusted.", "Couldn't unpack the update.",
                "No permission to replace the app here."),
    "ru":      ("Обновить сейчас", "Загружаю обновление…", "Не удалось установить обновление",
                "В релизе нет сборки для скачивания.", "Не удалось скачать.",
                "Контрольная сумма не совпала — загрузке нельзя доверять.", "Не удалось распаковать обновление.",
                "Нет прав заменить приложение здесь."),
    "de":      ("Jetzt aktualisieren", "Update wird geladen…", "Update konnte nicht installiert werden",
                "Das Release hat keinen ladbaren Build.", "Download fehlgeschlagen.",
                "Prüfsumme stimmt nicht — Download nicht vertrauenswürdig.", "Update konnte nicht entpackt werden.",
                "Keine Berechtigung, die App hier zu ersetzen."),
    "fr":      ("Mettre à jour", "Téléchargement de la mise à jour…", "Impossible d'installer la mise à jour",
                "La release n'a pas de build téléchargeable.", "Échec du téléchargement.",
                "La somme de contrôle ne correspond pas — téléchargement non fiable.", "Impossible de décompresser la mise à jour.",
                "Pas la permission de remplacer l'app ici."),
    "es":      ("Actualizar ahora", "Descargando la actualización…", "No se pudo instalar la actualización",
                "La versión no tiene una compilación descargable.", "Error de descarga.",
                "La suma de verificación no coincide — descarga no confiable.", "No se pudo descomprimir la actualización.",
                "Sin permiso para reemplazar la app aquí."),
    "it":      ("Aggiorna ora", "Download dell'aggiornamento…", "Impossibile installare l'aggiornamento",
                "La release non ha una build scaricabile.", "Download non riuscito.",
                "Checksum non corrispondente — download non attendibile.", "Impossibile decomprimere l'aggiornamento.",
                "Nessun permesso per sostituire l'app qui."),
    "pt-BR":   ("Atualizar agora", "Baixando a atualização…", "Não foi possível instalar a atualização",
                "A versão não tem um build para baixar.", "Falha no download.",
                "A soma de verificação não confere — download não confiável.", "Não foi possível descompactar a atualização.",
                "Sem permissão para substituir o app aqui."),
    "uk":      ("Оновити зараз", "Завантажую оновлення…", "Не вдалося встановити оновлення",
                "У релізі немає збірки для завантаження.", "Не вдалося завантажити.",
                "Контрольна сума не збіглася — завантаженню не можна довіряти.", "Не вдалося розпакувати оновлення.",
                "Немає прав замінити застосунок тут."),
    "pl":      ("Zaktualizuj teraz", "Pobieranie aktualizacji…", "Nie udało się zainstalować aktualizacji",
                "Wydanie nie ma pliku do pobrania.", "Pobieranie nie powiodło się.",
                "Suma kontrolna się nie zgadza — pobranie niewiarygodne.", "Nie udało się rozpakować aktualizacji.",
                "Brak uprawnień do zastąpienia aplikacji tutaj."),
    "tr":      ("Şimdi güncelle", "Güncelleme indiriliyor…", "Güncelleme yüklenemedi",
                "Sürümde indirilebilir derleme yok.", "İndirme başarısız.",
                "Sağlama toplamı uyuşmadı — indirme güvenilir değil.", "Güncelleme açılamadı.",
                "Uygulamayı burada değiştirme izni yok."),
    "ja":      ("今すぐ更新", "アップデートをダウンロード中…", "アップデートを適用できませんでした",
                "リリースにダウンロード可能なビルドがありません。", "ダウンロードに失敗しました。",
                "チェックサムが一致しません — ダウンロードは信頼できません。", "アップデートを展開できませんでした。",
                "ここでアプリを置き換える権限がありません。"),
    "ko":      ("지금 업데이트", "업데이트 다운로드 중…", "업데이트를 설치하지 못했습니다",
                "릴리스에 다운로드할 빌드가 없습니다.", "다운로드에 실패했습니다.",
                "체크섬이 일치하지 않습니다 — 다운로드를 신뢰할 수 없습니다.", "업데이트의 압축을 풀지 못했습니다.",
                "여기에서 앱을 교체할 권한이 없습니다."),
    "zh-Hans": ("立即更新", "正在下载更新…", "无法安装更新",
                "该发布没有可下载的构建。", "下载失败。",
                "校验和不匹配——下载不可信。", "无法解压更新。",
                "没有权限在此替换应用。"),
    "zh-Hant": ("立即更新", "正在下載更新…", "無法安裝更新",
                "此發布沒有可下載的建置。", "下載失敗。",
                "校驗碼不符——下載不可信。", "無法解壓更新。",
                "沒有權限在此替換應用程式。"),
}
_ABOUT = {
    "en": "About Notch Limits",          "ru": "О программе Notch Limits",
    "de": "Über Notch Limits",           "fr": "À propos de Notch Limits",
    "es": "Acerca de Notch Limits",      "it": "Informazioni su Notch Limits",
    "pt-BR": "Sobre o Notch Limits",     "uk": "Про Notch Limits",
    "pl": "O programie Notch Limits",    "tr": "Notch Limits hakkında",
    "ja": "Notch Limits について",        "ko": "Notch Limits 정보",
    "zh-Hans": "关于 Notch Limits",       "zh-Hant": "關於 Notch Limits",
}
for _lang, _about in _ABOUT.items():
    T[_lang]["menu.about"] = _about


for _lang, (_install, _installing, _installFailed, _noAsset, _dl, _checksum, _unpack, _notWritable) in _INSTALL.items():
    T[_lang]["update.install"] = _install
    T[_lang]["update.installing"] = _installing
    T[_lang]["update.installFailed"] = _installFailed
    T[_lang]["update.err.noAsset"] = _noAsset
    T[_lang]["update.err.download"] = _dl
    T[_lang]["update.err.checksum"] = _checksum
    T[_lang]["update.err.unpack"] = _unpack
    T[_lang]["update.err.notWritable"] = _notWritable


# Метка незавершённого профиля в списке удаления. Один «%@» — заголовок.
_INCOMPLETE = {
    "en": "%@ — not signed in",       "ru": "%@ — вход не выполнен",
    "de": "%@ — nicht angemeldet",    "fr": "%@ — non connecté",
    "es": "%@ — sin iniciar sesión",  "it": "%@ — accesso non eseguito",
    "pt-BR": "%@ — sem login",        "uk": "%@ — вхід не виконано",
    "pl": "%@ — niezalogowany",       "tr": "%@ — oturum açılmadı",
    "ja": "%@ — 未ログイン",           "ko": "%@ — 로그인 안 됨",
    "zh-Hans": "%@ — 未登录",          "zh-Hant": "%@ — 未登入",
}
for _lang, _text in _INCOMPLETE.items():
    T[_lang]["remove.incomplete"] = _text

# Перелогин одним нажатием: подпись чипа в колонке, его подсказка и строка
# в окне Terminal для Claude (там вход — командой /login внутри claude).
_REAUTH = {
    'en': ('re-auth', 'Open Terminal and sign in to this account again. The running app is not touched.',
        'Sign in in the browser. The status below must say "loggedIn": true; then close this window.'),
    'ru': ('re-auth', 'Открыть Terminal и заново войти в этот аккаунт. Запущенное приложение не трогаем.',
        'Войди в браузере. Ниже в статусе должно быть "loggedIn": true, потом закрой это окно.'),
    'de': ('Neu anmelden', 'Terminal öffnen und dieses Konto neu anmelden. Die laufende App bleibt unberührt.',
        'Melde dich im Browser an. Unten muss "loggedIn": true stehen; schließe dann dieses Fenster.'),
    'fr': ('Reconnexion', "Ouvrir Terminal et reconnecter ce compte. L'app en cours n'est pas touchée.",
        'Connectez-vous dans le navigateur. Le statut ci-dessous doit indiquer "loggedIn": true, puis fermez cette fenêtre.'),
    'es': ('Reautenticar', 'Abrir Terminal y volver a iniciar sesión en esta cuenta. La app en ejecución no se toca.',
        'Inicia sesión en el navegador. Abajo el estado debe decir "loggedIn": true; luego cierra esta ventana.'),
    'it': ('Riautentica', "Apri Terminale e accedi di nuovo a questo account. L'app in esecuzione non viene toccata.",
        'Accedi nel browser. Lo stato qui sotto deve indicare "loggedIn": true, poi chiudi questa finestra.'),
    'pt-BR': ('Reautenticar', 'Abrir o Terminal e entrar de novo nesta conta. O app em execução não é afetado.',
        'Entre no navegador. O status abaixo deve mostrar "loggedIn": true; depois feche esta janela.'),
    'uk': ('re-auth', 'Відкрити Terminal і знову увійти в цей акаунт. Запущений застосунок не чіпаємо.',
        'Увійди в браузері. Нижче в статусі має бути "loggedIn": true, потім закрий це вікно.'),
    'pl': ('re-auth', 'Otwórz Terminal i zaloguj się ponownie na to konto. Uruchomiona aplikacja pozostaje nietknięta.',
        'Zaloguj się w przeglądarce. Poniżej status musi pokazać "loggedIn": true, potem zamknij to okno.'),
    'tr': ('Yeniden giriş', "Terminal'i aç ve bu hesaba yeniden giriş yap. Çalışan uygulamaya dokunulmaz.",
        'Tarayıcıda giriş yap. Aşağıdaki durumda "loggedIn": true görünmeli; sonra bu pencereyi kapat.'),
    'ja': ('再認証', 'ターミナルを開いてこのアカウントに再ログインします。実行中のアプリには影響しません。',
        'ブラウザでログインしてください。下の状態が "loggedIn": true になったら、このウインドウを閉じてください。'),
    'ko': ('재인증', '터미널을 열어 이 계정에 다시 로그인합니다. 실행 중인 앱은 건드리지 않습니다.',
        '브라우저에서 로그인하세요. 아래 상태에 "loggedIn": true가 표시되면 이 창을 닫으세요.'),
    'zh-Hans': ('重新认证', '打开终端并重新登录此账户。正在运行的应用不受影响。',
        '在浏览器中登录。下方状态应显示 "loggedIn": true，然后关闭此窗口。'),
    'zh-Hant': ('重新認證', '打開終端機並重新登入此帳號。正在執行的 App 不受影響。',
        '在瀏覽器中登入。下方狀態應顯示 "loggedIn": true，然後關閉此視窗。'),
}
for _lang, (_chip, _help, _script) in _REAUTH.items():
    T[_lang]["column.reauth"] = _chip
    T[_lang]["column.reauth.help"] = _help
    T[_lang]["setup.script.reauth"] = _script


# Новые строки настройки аккаунтов и переключения приложений.
_ACCOUNT_UPDATES = {
    "en": {
        "setup.profile.hint": "Leave the name empty to sign in as the main account — the one the Claude/Codex app and the plain CLI use. For an extra account pick a short name, e.g. work: it becomes the column heading, and the CLI keeps its settings in a folder of that name.",
        "setup.profile.main": "Main account: %@",
        "setup.profile.mainReplaces": "Main account %@ — replaces the current sign-in.",
        "setup.badName.body": "Latin letters, digits, hyphen and underscore only, and the name must not be taken. Leave it empty for the main account.",
        "setup.script.relogin": "Already signed in — type /login to sign in to another account, then close this window.",
        "appswitch.title": "Claude app account",
        "appswitch.title.codex": "Codex app account",
        "appswitch.confirm.title": "Switch app account?",
        "appswitch.confirm.body": "%@ will quit and reopen as “%@”. The current session/chat will close.",
        "appswitch.confirm.do": "Switch and restart",
        "appswitch.error.title": "Couldn't switch the account",
        "appswitch.error.notInstalled": "%@ isn't installed.",
        "appswitch.error.didNotQuit": "%@ didn't quit — close it and try again.",
        "appswitch.error.noAuth": "This account has no Codex sign-in (auth.json). Sign in to it again."
    },
    "ru": {
        "setup.profile.hint": "Оставь имя пустым, чтобы войти основным аккаунтом — его используют приложение Claude/Codex и обычный CLI. Для дополнительного аккаунта придумай короткое имя, например work: оно станет заголовком колонки, а CLI будет держать настройки в папке с таким именем.",
        "setup.profile.main": "Основной аккаунт: %@",
        "setup.profile.mainReplaces": "Основной %@ — текущий вход заменится.",
        "setup.badName.body": "Только латиница, цифры, дефис и подчёркивание, и имя не должно быть занято. Для основного аккаунта оставь поле пустым.",
        "setup.script.relogin": "Вход уже есть — набери /login, чтобы войти в другой аккаунт, затем закрой это окно.",
        "appswitch.title": "Аккаунт приложения Claude",
        "appswitch.title.codex": "Аккаунт приложения Codex",
        "appswitch.confirm.title": "Переключить аккаунт приложения?",
        "appswitch.confirm.body": "%@ закроется и откроется под «%@». Текущая сессия/чат закроется.",
        "appswitch.confirm.do": "Переключить и перезапустить",
        "appswitch.error.title": "Не удалось переключить аккаунт",
        "appswitch.error.notInstalled": "%@ не установлен.",
        "appswitch.error.didNotQuit": "%@ не закрылся — закрой его и попробуй ещё раз.",
        "appswitch.error.noAuth": "У этого аккаунта нет входа в Codex (auth.json). Войди в него заново."
    },
    "de": {
        "setup.profile.hint": "Lass den Namen leer, um dich mit dem Hauptkonto anzumelden – dem Konto, das die Claude/Codex-App und die normale CLI nutzen. Für ein zusätzliches Konto wähle einen kurzen Namen, z. B. work: Er wird zur Spaltenüberschrift, und die CLI speichert ihre Einstellungen in einem Ordner mit diesem Namen.",
        "setup.profile.main": "Hauptkonto: %@",
        "setup.profile.mainReplaces": "Hauptkonto %@ – ersetzt die aktuelle Anmeldung.",
        "setup.badName.body": "Nur lateinische Buchstaben, Ziffern, Bindestrich und Unterstrich; der Name darf nicht vergeben sein. Für das Hauptkonto leer lassen.",
        "setup.script.relogin": "Bereits angemeldet – gib /login ein, um dich mit einem anderen Konto anzumelden, und schließe dann dieses Fenster.",
        "appswitch.title": "Claude-App-Konto",
        "appswitch.title.codex": "Codex-App-Konto",
        "appswitch.confirm.title": "App-Konto wechseln?",
        "appswitch.confirm.body": "%@ wird beendet und als „%@“ neu geöffnet. Die aktuelle Sitzung/Chat wird geschlossen.",
        "appswitch.confirm.do": "Wechseln und neu starten",
        "appswitch.error.title": "Konto konnte nicht gewechselt werden",
        "appswitch.error.notInstalled": "%@ ist nicht installiert.",
        "appswitch.error.didNotQuit": "%@ wurde nicht beendet – schließe die App und versuche es erneut.",
        "appswitch.error.noAuth": "Dieses Konto hat keine Codex-Anmeldung (auth.json). Melde dich erneut an."
    },
    "fr": {
        "setup.profile.hint": "Laissez le nom vide pour vous connecter avec le compte principal — celui qu’utilisent l’app Claude/Codex et la CLI habituelle. Pour un compte supplémentaire, choisissez un nom court, par exemple work : il devient le titre de la colonne, et la CLI range ses réglages dans un dossier de ce nom.",
        "setup.profile.main": "Compte principal : %@",
        "setup.profile.mainReplaces": "Compte principal %@ — remplace la connexion.",
        "setup.badName.body": "Lettres latines, chiffres, tiret et tiret bas uniquement, et le nom ne doit pas être déjà pris. Laissez vide pour le compte principal.",
        "setup.script.relogin": "Déjà connecté — tapez /login pour vous connecter à un autre compte, puis fermez cette fenêtre.",
        "appswitch.title": "Compte de l’app Claude",
        "appswitch.title.codex": "Compte de l’app Codex",
        "appswitch.confirm.title": "Changer le compte de l’app ?",
        "appswitch.confirm.body": "%@ va se fermer et rouvrir en « %@ ». La session/le chat en cours se fermera.",
        "appswitch.confirm.do": "Changer et redémarrer",
        "appswitch.error.title": "Impossible de changer de compte",
        "appswitch.error.notInstalled": "%@ n’est pas installé.",
        "appswitch.error.didNotQuit": "%@ ne s’est pas fermé — fermez-le et réessayez.",
        "appswitch.error.noAuth": "Ce compte n’a pas de connexion Codex (auth.json). Reconnectez-vous."
    },
    "es": {
        "setup.profile.hint": "Deja el nombre vacío para iniciar sesión con la cuenta principal, la que usan la app de Claude/Codex y la CLI normal. Para una cuenta adicional elige un nombre corto, por ejemplo work: será el título de la columna y la CLI guardará su configuración en una carpeta con ese nombre.",
        "setup.profile.main": "Cuenta principal: %@",
        "setup.profile.mainReplaces": "Cuenta principal %@: reemplaza la sesión actual.",
        "setup.badName.body": "Solo letras latinas, dígitos, guion y guion bajo, y el nombre no debe estar ocupado. Déjalo vacío para la cuenta principal.",
        "setup.script.relogin": "Ya hay una sesión: escribe /login para entrar con otra cuenta y luego cierra esta ventana.",
        "appswitch.title": "Cuenta de la app Claude",
        "appswitch.title.codex": "Cuenta de la app Codex",
        "appswitch.confirm.title": "¿Cambiar la cuenta de la app?",
        "appswitch.confirm.body": "%@ se cerrará y volverá a abrir como «%@». La sesión/chat actual se cerrará.",
        "appswitch.confirm.do": "Cambiar y reiniciar",
        "appswitch.error.title": "No se pudo cambiar la cuenta",
        "appswitch.error.notInstalled": "%@ no está instalado.",
        "appswitch.error.didNotQuit": "%@ no se cerró: ciérralo e inténtalo de nuevo.",
        "appswitch.error.noAuth": "Esta cuenta no tiene sesión de Codex (auth.json). Vuelve a iniciar sesión."
    },
    "it": {
        "setup.profile.hint": "Lascia il nome vuoto per accedere con l’account principale, quello usato dall’app Claude/Codex e dalla CLI normale. Per un account aggiuntivo scegli un nome breve, ad esempio work: diventa il titolo della colonna e la CLI salva le impostazioni in una cartella con quel nome.",
        "setup.profile.main": "Account principale: %@",
        "setup.profile.mainReplaces": "Account principale %@: sostituisce l’accesso.",
        "setup.badName.body": "Solo lettere latine, cifre, trattino e trattino basso, e il nome non deve essere già usato. Lascialo vuoto per l’account principale.",
        "setup.script.relogin": "Accesso già effettuato: digita /login per accedere a un altro account, poi chiudi questa finestra.",
        "appswitch.title": "Account app Claude",
        "appswitch.title.codex": "Account app Codex",
        "appswitch.confirm.title": "Cambiare account dell’app?",
        "appswitch.confirm.body": "%@ si chiuderà e riaprirà come «%@». La sessione/chat attuale si chiuderà.",
        "appswitch.confirm.do": "Cambia e riavvia",
        "appswitch.error.title": "Impossibile cambiare account",
        "appswitch.error.notInstalled": "%@ non è installato.",
        "appswitch.error.didNotQuit": "%@ non si è chiuso: chiudilo e riprova.",
        "appswitch.error.noAuth": "Questo account non ha un accesso a Codex (auth.json). Accedi di nuovo."
    },
    "pt-BR": {
        "setup.profile.hint": "Deixe o nome vazio para entrar com a conta principal — a usada pelo app Claude/Codex e pela CLI comum. Para uma conta extra, escolha um nome curto, por exemplo work: ele vira o título da coluna, e a CLI guarda as configurações numa pasta com esse nome.",
        "setup.profile.main": "Conta principal: %@",
        "setup.profile.mainReplaces": "Conta principal %@ — substitui o login atual.",
        "setup.badName.body": "Apenas letras latinas, dígitos, hífen e sublinhado, e o nome não pode estar em uso. Deixe vazio para a conta principal.",
        "setup.script.relogin": "Já existe um login — digite /login para entrar em outra conta e depois feche esta janela.",
        "appswitch.title": "Conta do app Claude",
        "appswitch.title.codex": "Conta do app Codex",
        "appswitch.confirm.title": "Trocar a conta do app?",
        "appswitch.confirm.body": "O %@ vai fechar e reabrir como “%@”. A sessão/chat atual será fechada.",
        "appswitch.confirm.do": "Trocar e reiniciar",
        "appswitch.error.title": "Não foi possível trocar de conta",
        "appswitch.error.notInstalled": "%@ não está instalado.",
        "appswitch.error.didNotQuit": "%@ não foi fechado — feche-o e tente novamente.",
        "appswitch.error.noAuth": "Esta conta não tem login no Codex (auth.json). Entre novamente."
    },
    "uk": {
        "setup.profile.hint": "Залиш ім’я порожнім, щоб увійти основним акаунтом — його використовують застосунок Claude/Codex і звичайний CLI. Для додаткового акаунта придумай коротке ім’я, наприклад work: воно стане заголовком колонки, а CLI зберігатиме налаштування в теці з таким ім’ям.",
        "setup.profile.main": "Основний акаунт: %@",
        "setup.profile.mainReplaces": "Основний %@ — поточний вхід буде замінено.",
        "setup.badName.body": "Лише латиниця, цифри, дефіс і підкреслення, і ім’я не має бути зайняте. Для основного акаунта залиш поле порожнім.",
        "setup.script.relogin": "Вхід уже є — набери /login, щоб увійти в інший акаунт, потім закрий це вікно.",
        "appswitch.title": "Акаунт застосунку Claude",
        "appswitch.title.codex": "Акаунт застосунку Codex",
        "appswitch.confirm.title": "Перемкнути акаунт застосунку?",
        "appswitch.confirm.body": "%@ закриється і відкриється як «%@». Поточна сесія/чат закриється.",
        "appswitch.confirm.do": "Перемкнути й перезапустити",
        "appswitch.error.title": "Не вдалося перемкнути акаунт",
        "appswitch.error.notInstalled": "%@ не встановлено.",
        "appswitch.error.didNotQuit": "%@ не закрився — закрий його й спробуй ще раз.",
        "appswitch.error.noAuth": "У цього акаунта немає входу в Codex (auth.json). Увійди в нього знову."
    },
    "pl": {
        "setup.profile.hint": "Zostaw nazwę pustą, aby zalogować się kontem głównym — tym, którego używają aplikacja Claude/Codex i zwykłe CLI. Dla dodatkowego konta wymyśl krótką nazwę, np. work: stanie się nagłówkiem kolumny, a CLI będzie trzymać ustawienia w folderze o tej nazwie.",
        "setup.profile.main": "Konto główne: %@",
        "setup.profile.mainReplaces": "Konto główne %@ — zastąpi obecne logowanie.",
        "setup.badName.body": "Tylko litery łacińskie, cyfry, myślnik i podkreślenie, a nazwa nie może być zajęta. Dla konta głównego zostaw pole puste.",
        "setup.script.relogin": "Już zalogowano — wpisz /login, aby zalogować się na inne konto, potem zamknij to okno.",
        "appswitch.title": "Konto aplikacji Claude",
        "appswitch.title.codex": "Konto aplikacji Codex",
        "appswitch.confirm.title": "Przełączyć konto aplikacji?",
        "appswitch.confirm.body": "%@ zamknie się i otworzy jako „%@”. Bieżąca sesja/czat zostanie zamknięta.",
        "appswitch.confirm.do": "Przełącz i uruchom ponownie",
        "appswitch.error.title": "Nie udało się przełączyć konta",
        "appswitch.error.notInstalled": "%@ nie jest zainstalowany.",
        "appswitch.error.didNotQuit": "%@ się nie zamknął — zamknij go i spróbuj ponownie.",
        "appswitch.error.noAuth": "To konto nie ma logowania do Codex (auth.json). Zaloguj się ponownie."
    },
    "tr": {
        "setup.profile.hint": "Ana hesapla giriş yapmak için adı boş bırak — Claude/Codex uygulamasının ve normal CLI'ın kullandığı hesap. Ek hesap için kısa bir ad seç, örneğin work: sütun başlığı olur ve CLI ayarlarını bu adlı klasörde tutar.",
        "setup.profile.main": "Ana hesap: %@",
        "setup.profile.mainReplaces": "Ana hesap %@ — mevcut girişin yerine geçer.",
        "setup.badName.body": "Yalnızca Latin harfleri, rakamlar, tire ve alt çizgi; ad kullanımda olmamalı. Ana hesap için boş bırak.",
        "setup.script.relogin": "Zaten giriş yapılmış — başka bir hesaba girmek için /login yaz, sonra bu pencereyi kapat.",
        "appswitch.title": "Claude uygulama hesabı",
        "appswitch.title.codex": "Codex uygulama hesabı",
        "appswitch.confirm.title": "Uygulama hesabı değiştirilsin mi?",
        "appswitch.confirm.body": "%@ kapanıp “%@” olarak yeniden açılacak. Mevcut oturum/sohbet kapanacak.",
        "appswitch.confirm.do": "Değiştir ve yeniden başlat",
        "appswitch.error.title": "Hesap değiştirilemedi",
        "appswitch.error.notInstalled": "%@ yüklü değil.",
        "appswitch.error.didNotQuit": "%@ kapanmadı — kapatıp tekrar dene.",
        "appswitch.error.noAuth": "Bu hesabın Codex oturumu (auth.json) yok. Yeniden giriş yap."
    },
    "ja": {
        "setup.profile.hint": "名前を空欄にするとメインアカウントでサインインします（Claude/Codex アプリと通常の CLI が使うアカウント）。追加アカウントには work などの短い名前を付けてください。列の見出しになり、CLI はその名前のフォルダに設定を保存します。",
        "setup.profile.main": "メインアカウント: %@",
        "setup.profile.mainReplaces": "メイン %@ — 現在のサインインを置き換えます。",
        "setup.badName.body": "使えるのはラテン文字、数字、ハイフン、アンダースコアのみで、既存の名前は使えません。メインアカウントは空欄のままにします。",
        "setup.script.relogin": "すでにサインインしています。別のアカウントにするには /login と入力し、その後このウインドウを閉じてください。",
        "appswitch.title": "Claude アプリのアカウント",
        "appswitch.title.codex": "Codex アプリのアカウント",
        "appswitch.confirm.title": "アプリのアカウントを切り替えますか？",
        "appswitch.confirm.body": "%@ を終了し「%@」で開き直します。現在のセッション/チャットは閉じます。",
        "appswitch.confirm.do": "切り替えて再起動",
        "appswitch.error.title": "アカウントを切り替えられませんでした",
        "appswitch.error.notInstalled": "%@ がインストールされていません。",
        "appswitch.error.didNotQuit": "%@ が終了しませんでした。終了してからもう一度お試しください。",
        "appswitch.error.noAuth": "このアカウントには Codex のサインイン (auth.json) がありません。もう一度サインインしてください。"
    },
    "ko": {
        "setup.profile.hint": "이름을 비워 두면 기본 계정으로 로그인합니다(Claude/Codex 앱과 일반 CLI가 쓰는 계정). 추가 계정에는 work 같은 짧은 이름을 정하세요. 열 제목이 되고, CLI는 그 이름의 폴더에 설정을 보관합니다.",
        "setup.profile.main": "기본 계정: %@",
        "setup.profile.mainReplaces": "기본 계정 %@ — 현재 로그인을 교체합니다.",
        "setup.badName.body": "라틴 문자, 숫자, 하이픈, 밑줄만 쓸 수 있고 이미 있는 이름은 안 됩니다. 기본 계정은 비워 두세요.",
        "setup.script.relogin": "이미 로그인되어 있습니다. 다른 계정으로 로그인하려면 /login을 입력한 뒤 이 창을 닫으세요.",
        "appswitch.title": "Claude 앱 계정",
        "appswitch.title.codex": "Codex 앱 계정",
        "appswitch.confirm.title": "앱 계정을 전환할까요?",
        "appswitch.confirm.body": "%@가 종료되고 “%@”로 다시 열립니다. 현재 세션/채팅이 닫힙니다.",
        "appswitch.confirm.do": "전환 후 재시작",
        "appswitch.error.title": "계정을 전환하지 못했습니다",
        "appswitch.error.notInstalled": "%@이(가) 설치되어 있지 않습니다.",
        "appswitch.error.didNotQuit": "%@이(가) 종료되지 않았습니다. 앱을 닫고 다시 시도하세요.",
        "appswitch.error.noAuth": "이 계정에는 Codex 로그인(auth.json)이 없습니다. 다시 로그인하세요."
    },
    "zh-Hans": {
        "setup.profile.hint": "名称留空即以主账户登录——Claude/Codex 应用和普通 CLI 使用的账户。额外账户请起一个简短名称，例如 work：它会成为列标题，CLI 会把设置保存在同名文件夹中。",
        "setup.profile.main": "主账户：%@",
        "setup.profile.mainReplaces": "主账户 %@——将替换当前登录。",
        "setup.badName.body": "只能使用拉丁字母、数字、连字符和下划线，且名称不能已被占用。主账户请留空。",
        "setup.script.relogin": "已登录——输入 /login 以登录其他账户，然后关闭此窗口。",
        "appswitch.title": "Claude 应用账户",
        "appswitch.title.codex": "Codex 应用账户",
        "appswitch.confirm.title": "切换应用账户？",
        "appswitch.confirm.body": "%@ 将退出并以“%@”重新打开。当前会话/聊天将关闭。",
        "appswitch.confirm.do": "切换并重启",
        "appswitch.error.title": "无法切换账户",
        "appswitch.error.notInstalled": "未安装 %@。",
        "appswitch.error.didNotQuit": "%@ 未退出——请关闭后重试。",
        "appswitch.error.noAuth": "此账户没有 Codex 登录信息 (auth.json)。请重新登录。"
    },
    "zh-Hant": {
        "setup.profile.hint": "名稱留空即以主帳號登入——Claude/Codex App 與一般 CLI 使用的帳號。額外帳號請取一個簡短名稱，例如 work：它會成為欄位標題，CLI 會把設定存放在同名資料夾中。",
        "setup.profile.main": "主帳號：%@",
        "setup.profile.mainReplaces": "主帳號 %@——將取代目前的登入。",
        "setup.badName.body": "只能使用拉丁字母、數字、連字號與底線，且名稱不能已被使用。主帳號請留空。",
        "setup.script.relogin": "已登入——輸入 /login 以登入其他帳號，然後關閉此視窗。",
        "appswitch.title": "Claude 應用程式帳戶",
        "appswitch.title.codex": "Codex 應用程式帳戶",
        "appswitch.confirm.title": "切換應用程式帳戶？",
        "appswitch.confirm.body": "%@ 將結束並以「%@」重新開啟。目前工作階段/對話將關閉。",
        "appswitch.confirm.do": "切換並重新啟動",
        "appswitch.error.title": "無法切換帳號",
        "appswitch.error.notInstalled": "未安裝 %@。",
        "appswitch.error.didNotQuit": "%@ 未結束——請關閉後再試一次。",
        "appswitch.error.noAuth": "此帳號沒有 Codex 登入資訊 (auth.json)。請重新登入。"
    }
}
for _lang, _values in _ACCOUNT_UPDATES.items():
    T[_lang].update(_values)
# Продление Claude без права записи в Keychain опасно — показываем причину.
_KEYCHAIN_WRITE = {'en': 'no Keychain write access', 'ru': 'нет записи в Keychain', 'de': 'kein Schreibzugriff auf den Schlüsselbund', 'fr': "pas d'accès en écriture au trousseau", 'es': 'sin escritura en el llavero', 'it': 'nessuna scrittura nel portachiavi', 'pt-BR': 'sem gravação no Keychain', 'uk': 'немає запису в Keychain', 'pl': 'brak zapisu do pęku kluczy', 'tr': "Anahtar Zinciri'ne yazılamıyor", 'ja': 'キーチェーンに書き込めません', 'ko': '키체인에 쓸 수 없음', 'zh-Hans': '无法写入钥匙串', 'zh-Hant': '無法寫入鑰匙圈'}
for _lang, _text in _KEYCHAIN_WRITE.items():
    T[_lang]["error.keychainWrite"] = _text


def main():
    keys = [key for _, group in ORDER for key in group]
    base = T["en"]

    missing_report = []
    for language, table in T.items():
        absent = [key for key in keys if key not in table]
        extra = [key for key in table if key not in keys]
        if absent:
            missing_report.append("%s: нет ключей %s" % (language, ", ".join(absent)))
        if extra:
            missing_report.append("%s: лишние ключи %s" % (language, ", ".join(extra)))
    if missing_report:
        raise SystemExit("\n".join(missing_report))

    for language, table in sorted(T.items()):
        directory = os.path.join("Resources", language + ".lproj")
        os.makedirs(directory, exist_ok=True)
        lines = ["/* NotchLimits — %s. Собрано Tools/make-strings.py */" % language]
        for title, group in ORDER:
            lines.append("")
            lines.append("// " + title)
            for key in group:
                value = table.get(key, base[key]).replace('"', '\\"')
                lines.append('"%s" = "%s";' % (key, value))
        path = os.path.join(directory, "Localizable.strings")
        with io.open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines) + "\n")
        print("%-8s %d ключей" % (language, len(keys)))

    print("языков: %d" % len(T))


if __name__ == "__main__":
    main()
