#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генератор Resources/<язык>.lproj/Localizable.strings.

    python3 Tools/make-strings.py

Единственный источник правды по переводам. Английский — запасной язык
(CFBundleDevelopmentRegion), из него же берутся значения для ключей,
которых нет в конкретном переводе.

Единицы времени намеренно сокращены: так строки не зависят от правил
множественного числа, которые в русском, польском и украинском разные.
Только LTR-языки — зеркалить макет панели не требуется.
"""
import io
import os

ORDER = [
    ("Окна лимитов и время", [
        "reset.days", "reset.hours", "reset.minutes", "reset.imminent",
        "age.justNow", "age.seconds", "age.minutes", "age.hours", "age.days",
        "window.fiveHour", "window.week", "window.hours", "window.days",
        "window.generic", "format.percent",
    ]),
    ("Колонка", [
        "column.updating", "column.stale",
        "column.reauth.claude", "column.reauth.codex",
    ]),
    ("Панель", [
        "panel.updated", "panel.noData", "panel.refresh.help",
        "panel.empty.title", "panel.empty.hint",
        "panel.hidden.title", "panel.hidden.hint",
    ]),
    ("Контекстное меню", [
        "menu.refresh", "menu.addClaude", "menu.addCodex", "menu.hideColumn",
        "menu.noColumns", "menu.renameColumn", "menu.showHidden", "menu.hotKey",
        "menu.hotKey.change", "menu.hotKey.standard", "menu.hotKey.disable",
        "menu.loginItem", "menu.quit",
    ]),
    ("Горячая клавиша", [
        "hotkey.disabled", "hotkey.recorder.title", "hotkey.recorder.hint",
        "hotkey.recorder.save", "hotkey.taken.title", "hotkey.taken.body",
    ]),
    ("Переименование колонки", ["rename.title", "rename.hint"]),
    ("Общее", ["common.ok", "common.cancel", "common.save"]),
    ("Добавление аккаунта", [
        "setup.claude.title", "setup.codex.title", "setup.profile.hint",
        "setup.profile.terminal", "setup.profile.folder",
        "setup.profile.badChars", "setup.profile.exists", "setup.create",
        "setup.badName.title", "setup.badName.body", "setup.failed.title",
        "setup.missing.title", "setup.missing.body",
        "setup.script.profile", "setup.script.hint", "loginItem.failed.title",
    ]),
    ("Статистика под окнами", [
        "stat.credits", "stat.unlimited", "stat.resetCredits", "stat.extraUsage",
    ]),
    ("Прогноз исчерпания", ["burn.limitAt"]),
    ("Уведомления", ["notification.title", "notification.body",
                     "notification.reset.title", "notification.reset.body"]),
    ("Ошибки в колонке", [
        "error.network", "error.timeout", "error.noHTTP", "error.http",
        "error.parse", "error.unknownSource", "error.noProvider",
        "error.unreachable",
    ]),
]

T = {}

T["en"] = {
    "reset.days": "Resets in %1$dd %2$dh",
    "reset.hours": "Resets in %1$dh %2$dm",
    "reset.minutes": "Resets in %dm",
    "reset.imminent": "Resetting now",
    "age.justNow": "just now",
    "age.seconds": "%ds ago", "age.minutes": "%dm ago",
    "age.hours": "%dh ago", "age.days": "%dd ago",
    "window.fiveHour": "5-hour window", "window.week": "Weekly window",
    "window.hours": "%d-hour window", "window.days": "%d-day window",
    "window.generic": "Limit window", "format.percent": "%d%%",
    "column.updating": "refreshing…", "column.stale": "data from %@",
    "column.reauth.claude": "re-auth: run claude",
    "column.reauth.codex": "re-auth: run codex",
    "panel.updated": "Updated %@", "panel.noData": "No data yet",
    "panel.refresh.help": "Refresh all columns",
    "panel.empty.title": "No accounts",
    "panel.empty.hint": "Right-click → “Add Claude account…” or “Add Codex account…”",
    "panel.hidden.title": "All columns hidden",
    "panel.hidden.hint": "Right-click → “Show hidden columns”",
    "menu.refresh": "Refresh", "menu.addClaude": "Add Claude account…",
    "menu.addCodex": "Add Codex account…", "menu.hideColumn": "Hide column",
    "menu.noColumns": "No columns", "menu.showHidden": "Show hidden columns",
    "menu.renameColumn": "Rename column",
    "rename.title": "Column name",
    "rename.hint": "How this column is labelled. Leave empty to go back to “%@”.",
    "common.save": "Save",
    "menu.hotKey": "Shortcut: %@", "menu.hotKey.change": "Change…",
    "menu.hotKey.standard": "Default (⌘P)", "menu.hotKey.disable": "Turn off",
    "menu.loginItem": "Launch at login", "menu.quit": "Quit",
    "hotkey.disabled": "off", "hotkey.recorder.title": "Shortcut",
    "hotkey.recorder.hint": "Press a combination — it must include ⌘, ⌥ or ⌃.",
    "hotkey.recorder.save": "Save",
    "hotkey.taken.title": "%@ is already taken",
    "hotkey.taken.body": "Another app already holds it. Your previous shortcut is unchanged.",
    "common.ok": "OK", "common.cancel": "Cancel",
    "setup.claude.title": "New Claude account",
    "setup.codex.title": "New Codex account",
    "setup.profile.hint": "Pick a short name for this account — for example work or personal. It becomes the column heading, and the CLI keeps its settings in a folder of that name.",
    "setup.profile.terminal": "After you click Create, Terminal opens — sign in there.",
    "setup.profile.folder": "Folder: %@",
    "setup.profile.badChars": "Latin letters, digits, hyphen and underscore only.",
    "setup.profile.exists": "A profile with this name already exists.",
    "setup.create": "Create", "setup.badName.title": "Bad profile name",
    "setup.badName.body": "Latin letters, digits, hyphen and underscore only. The name must not be empty or already taken.",
    "setup.failed.title": "Could not create the profile",
    "setup.missing.title": "Couldn’t find %@",
    "setup.missing.body": "Install the CLI and try again:\\n\\n%@",
    "setup.script.profile": "Profile: %@",
    "setup.script.hint": "Sign in, then close this window.",
    "loginItem.failed.title": "Could not change launch at login",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "network error", "error.timeout": "timeout",
    "error.noHTTP": "no HTTP response", "error.http": "HTTP %d",
    "error.parse": "could not parse response",
    "error.unknownSource": "unknown source", "error.noProvider": "no provider",
    "error.unreachable": "network unavailable",
}

T["ru"] = {
    "reset.days": "Сброс через %1$d д %2$d ч",
    "reset.hours": "Сброс через %1$d ч %2$d мин",
    "reset.minutes": "Сброс через %d мин",
    "reset.imminent": "Сброс вот-вот",
    "age.justNow": "только что",
    "age.seconds": "%d с назад", "age.minutes": "%d мин назад",
    "age.hours": "%d ч назад", "age.days": "%d д назад",
    "window.fiveHour": "5-часовое окно", "window.week": "Недельное окно",
    "window.hours": "%d-часовое окно", "window.days": "%d-дневное окно",
    "window.generic": "Окно лимита", "format.percent": "%d %%",
    "column.updating": "обновляю…", "column.stale": "данные %@",
    "column.reauth.claude": "re-auth: запусти claude",
    "column.reauth.codex": "re-auth: запусти codex",
    "panel.updated": "Обновлено %@", "panel.noData": "Данных ещё нет",
    "panel.refresh.help": "Обновить все колонки",
    "panel.empty.title": "Нет аккаунтов",
    "panel.empty.hint": "Правый клик → «Добавить аккаунт Claude…» или «Добавить аккаунт Codex…»",
    "panel.hidden.title": "Все колонки скрыты",
    "panel.hidden.hint": "Правый клик → «Показать скрытые колонки»",
    "menu.refresh": "Обновить", "menu.addClaude": "Добавить аккаунт Claude…",
    "menu.addCodex": "Добавить аккаунт Codex…", "menu.hideColumn": "Скрыть колонку",
    "menu.noColumns": "Нет колонок", "menu.showHidden": "Показать скрытые колонки",
    "menu.renameColumn": "Переименовать колонку",
    "rename.title": "Имя колонки",
    "rename.hint": "Как подписать эту колонку. Пусто — вернуть «%@».",
    "common.save": "Сохранить",
    "menu.hotKey": "Горячая клавиша: %@", "menu.hotKey.change": "Изменить…",
    "menu.hotKey.standard": "Стандартная (⌘P)", "menu.hotKey.disable": "Выключить",
    "menu.loginItem": "Запуск при входе", "menu.quit": "Выход",
    "hotkey.disabled": "выключена", "hotkey.recorder.title": "Горячая клавиша",
    "hotkey.recorder.hint": "Нажми сочетание — обязательно с ⌘, ⌥ или ⌃.",
    "hotkey.recorder.save": "Сохранить",
    "hotkey.taken.title": "Сочетание %@ занято",
    "hotkey.taken.body": "Его уже держит другое приложение. Прежняя настройка осталась без изменений.",
    "common.ok": "Ок", "common.cancel": "Отмена",
    "setup.claude.title": "Новый аккаунт Claude",
    "setup.codex.title": "Новый аккаунт Codex",
    "setup.profile.hint": "Придумай короткое имя для этого аккаунта — например work или personal. Оно станет заголовком колонки, а CLI будет держать настройки в папке с таким именем.",
    "setup.profile.terminal": "После «Создать» откроется Терминал — вход в аккаунт делается там.",
    "setup.profile.folder": "Папка: %@",
    "setup.profile.badChars": "Только латиница, цифры, дефис и подчёркивание.",
    "setup.profile.exists": "Профиль с таким именем уже есть.",
    "setup.create": "Создать", "setup.badName.title": "Плохое имя профиля",
    "setup.badName.body": "Только латиница, цифры, дефис и подчёркивание. Имя не должно быть пустым или уже занятым.",
    "setup.failed.title": "Не получилось создать профиль",
    "setup.missing.title": "Не нашёл %@",
    "setup.missing.body": "Установи CLI и попробуй снова:\\n\\n%@",
    "setup.script.profile": "Профиль: %@",
    "setup.script.hint": "Войди в аккаунт, затем закрой это окно.",
    "loginItem.failed.title": "Не получилось изменить запуск при входе",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "сбой сети", "error.timeout": "таймаут",
    "error.noHTTP": "нет HTTP-ответа", "error.http": "HTTP %d",
    "error.parse": "не разобрал ответ",
    "error.unknownSource": "неизвестный источник", "error.noProvider": "нет провайдера",
    "error.unreachable": "сеть недоступна",
}

T["de"] = {
    "reset.days": "Zurücksetzung in %1$d T %2$d Std",
    "reset.hours": "Zurücksetzung in %1$d Std %2$d Min",
    "reset.minutes": "Zurücksetzung in %d Min",
    "reset.imminent": "Wird gerade zurückgesetzt",
    "age.justNow": "gerade eben",
    "age.seconds": "vor %d s", "age.minutes": "vor %d Min",
    "age.hours": "vor %d Std", "age.days": "vor %d T",
    "window.fiveHour": "5-Stunden-Fenster", "window.week": "Wochenfenster",
    "window.hours": "%d-Stunden-Fenster", "window.days": "%d-Tage-Fenster",
    "window.generic": "Limitfenster", "format.percent": "%d %%",
    "column.updating": "wird aktualisiert…", "column.stale": "Daten von %@",
    "column.reauth.claude": "Neu anmelden: claude starten",
    "column.reauth.codex": "Neu anmelden: codex starten",
    "panel.updated": "Aktualisiert %@", "panel.noData": "Noch keine Daten",
    "panel.refresh.help": "Alle Spalten aktualisieren",
    "panel.empty.title": "Keine Accounts",
    "panel.empty.hint": "Rechtsklick → „Claude-Account hinzufügen…“ oder „Codex-Account hinzufügen…“",
    "panel.hidden.title": "Alle Spalten ausgeblendet",
    "panel.hidden.hint": "Rechtsklick → „Ausgeblendete Spalten zeigen“",
    "menu.refresh": "Aktualisieren", "menu.addClaude": "Claude-Account hinzufügen…",
    "menu.addCodex": "Codex-Account hinzufügen…", "menu.hideColumn": "Spalte ausblenden",
    "menu.noColumns": "Keine Spalten", "menu.showHidden": "Ausgeblendete Spalten zeigen",
    "menu.renameColumn": "Spalte umbenennen",
    "rename.title": "Spaltenname",
    "rename.hint": "Wie diese Spalte beschriftet wird. Leer lassen, um zu „%@“ zurückzukehren.",
    "common.save": "Sichern",
    "menu.hotKey": "Tastenkürzel: %@", "menu.hotKey.change": "Ändern…",
    "menu.hotKey.standard": "Standard (⌘P)", "menu.hotKey.disable": "Ausschalten",
    "menu.loginItem": "Beim Anmelden starten", "menu.quit": "Beenden",
    "hotkey.disabled": "aus", "hotkey.recorder.title": "Tastenkürzel",
    "hotkey.recorder.hint": "Drücke eine Kombination — mit ⌘, ⌥ oder ⌃.",
    "hotkey.recorder.save": "Sichern",
    "hotkey.taken.title": "%@ ist bereits belegt",
    "hotkey.taken.body": "Eine andere App belegt es bereits. Die vorherige Einstellung bleibt unverändert.",
    "common.ok": "OK", "common.cancel": "Abbrechen",
    "setup.claude.title": "Neuer Claude-Account",
    "setup.codex.title": "Neuer Codex-Account",
    "setup.profile.hint": "Wähle einen kurzen Namen für diesen Account — etwa work oder personal. Er wird zur Spaltenüberschrift, und das CLI legt seine Einstellungen in einem Ordner dieses Namens ab.",
    "setup.profile.terminal": "Nach „Erstellen“ öffnet sich das Terminal — melde dich dort an.",
    "setup.profile.folder": "Ordner: %@",
    "setup.profile.badChars": "Nur lateinische Buchstaben, Ziffern, Bindestrich und Unterstrich.",
    "setup.profile.exists": "Ein Profil mit diesem Namen existiert bereits.",
    "setup.create": "Erstellen", "setup.badName.title": "Ungültiger Profilname",
    "setup.badName.body": "Nur lateinische Buchstaben, Ziffern, Bindestrich und Unterstrich. Der Name darf nicht leer oder schon vergeben sein.",
    "setup.failed.title": "Profil konnte nicht erstellt werden",
    "setup.missing.title": "%@ nicht gefunden",
    "setup.missing.body": "Installiere das CLI und versuche es erneut:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Melde dich an und schliesse dieses Fenster.",
    "loginItem.failed.title": "Anmeldeobjekt konnte nicht geändert werden",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "Netzwerkfehler", "error.timeout": "Zeitüberschreitung",
    "error.noHTTP": "keine HTTP-Antwort", "error.http": "HTTP %d",
    "error.parse": "Antwort nicht lesbar",
    "error.unknownSource": "unbekannte Quelle", "error.noProvider": "kein Anbieter",
    "error.unreachable": "Netzwerk nicht verfügbar",
}

T["fr"] = {
    "reset.days": "Réinitialisation dans %1$d j %2$d h",
    "reset.hours": "Réinitialisation dans %1$d h %2$d min",
    "reset.minutes": "Réinitialisation dans %d min",
    "reset.imminent": "Réinitialisation imminente",
    "age.justNow": "à l’instant",
    "age.seconds": "il y a %d s", "age.minutes": "il y a %d min",
    "age.hours": "il y a %d h", "age.days": "il y a %d j",
    "window.fiveHour": "Fenêtre de 5 h", "window.week": "Fenêtre hebdomadaire",
    "window.hours": "Fenêtre de %d h", "window.days": "Fenêtre de %d j",
    "window.generic": "Fenêtre de limite", "format.percent": "%d %%",
    "column.updating": "actualisation…", "column.stale": "données %@",
    "column.reauth.claude": "reconnexion : lancez claude",
    "column.reauth.codex": "reconnexion : lancez codex",
    "panel.updated": "Mis à jour %@", "panel.noData": "Pas encore de données",
    "panel.refresh.help": "Actualiser toutes les colonnes",
    "panel.empty.title": "Aucun compte",
    "panel.empty.hint": "Clic droit → « Ajouter un compte Claude… » ou « Ajouter un compte Codex… »",
    "panel.hidden.title": "Toutes les colonnes sont masquées",
    "panel.hidden.hint": "Clic droit → « Afficher les colonnes masquées »",
    "menu.refresh": "Actualiser", "menu.addClaude": "Ajouter un compte Claude…",
    "menu.addCodex": "Ajouter un compte Codex…", "menu.hideColumn": "Masquer une colonne",
    "menu.noColumns": "Aucune colonne", "menu.showHidden": "Afficher les colonnes masquées",
    "menu.renameColumn": "Renommer la colonne",
    "rename.title": "Nom de la colonne",
    "rename.hint": "Le libellé de cette colonne. Laissez vide pour revenir à « %@ ».",
    "common.save": "Enregistrer",
    "menu.hotKey": "Raccourci : %@", "menu.hotKey.change": "Modifier…",
    "menu.hotKey.standard": "Par défaut (⌘P)", "menu.hotKey.disable": "Désactiver",
    "menu.loginItem": "Lancer à l’ouverture de session", "menu.quit": "Quitter",
    "hotkey.disabled": "désactivé", "hotkey.recorder.title": "Raccourci",
    "hotkey.recorder.hint": "Appuyez sur une combinaison — avec ⌘, ⌥ ou ⌃.",
    "hotkey.recorder.save": "Enregistrer",
    "hotkey.taken.title": "%@ est déjà utilisé",
    "hotkey.taken.body": "Une autre app l’utilise déjà. Votre réglage précédent est conservé.",
    "common.ok": "OK", "common.cancel": "Annuler",
    "setup.claude.title": "Nouveau compte Claude",
    "setup.codex.title": "Nouveau compte Codex",
    "setup.profile.hint": "Choisissez un nom court pour ce compte — par exemple work ou personal. Il servira de titre de colonne, et le CLI rangera ses réglages dans un dossier de ce nom.",
    "setup.profile.terminal": "Après « Créer », le Terminal s’ouvre — connectez-vous là.",
    "setup.profile.folder": "Dossier : %@",
    "setup.profile.badChars": "Lettres latines, chiffres, tiret et tiret bas uniquement.",
    "setup.profile.exists": "Un profil de ce nom existe déjà.",
    "setup.create": "Créer", "setup.badName.title": "Nom de profil invalide",
    "setup.badName.body": "Lettres latines, chiffres, tiret et tiret bas uniquement. Le nom ne doit être ni vide ni déjà pris.",
    "setup.failed.title": "Impossible de créer le profil",
    "setup.missing.title": "Impossible de trouver %@",
    "setup.missing.body": "Installez le CLI puis réessayez :\\n\\n%@",
    "setup.script.profile": "Profil : %@",
    "setup.script.hint": "Connectez-vous, puis fermez cette fenetre.",
    "loginItem.failed.title": "Impossible de modifier le lancement à l’ouverture",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@ : %2$d %%",
    "error.network": "erreur réseau", "error.timeout": "délai dépassé",
    "error.noHTTP": "pas de réponse HTTP", "error.http": "HTTP %d",
    "error.parse": "réponse illisible",
    "error.unknownSource": "source inconnue", "error.noProvider": "aucun fournisseur",
    "error.unreachable": "réseau indisponible",
}

T["es"] = {
    "reset.days": "Se reinicia en %1$d d %2$d h",
    "reset.hours": "Se reinicia en %1$d h %2$d min",
    "reset.minutes": "Se reinicia en %d min",
    "reset.imminent": "Reiniciando ahora",
    "age.justNow": "ahora mismo",
    "age.seconds": "hace %d s", "age.minutes": "hace %d min",
    "age.hours": "hace %d h", "age.days": "hace %d d",
    "window.fiveHour": "Ventana de 5 h", "window.week": "Ventana semanal",
    "window.hours": "Ventana de %d h", "window.days": "Ventana de %d d",
    "window.generic": "Ventana de límite", "format.percent": "%d %%",
    "column.updating": "actualizando…", "column.stale": "datos de %@",
    "column.reauth.claude": "reautenticar: ejecuta claude",
    "column.reauth.codex": "reautenticar: ejecuta codex",
    "panel.updated": "Actualizado %@", "panel.noData": "Aún no hay datos",
    "panel.refresh.help": "Actualizar todas las columnas",
    "panel.empty.title": "Sin cuentas",
    "panel.empty.hint": "Clic derecho → «Añadir cuenta de Claude…» o «Añadir cuenta de Codex…»",
    "panel.hidden.title": "Todas las columnas ocultas",
    "panel.hidden.hint": "Clic derecho → «Mostrar columnas ocultas»",
    "menu.refresh": "Actualizar", "menu.addClaude": "Añadir cuenta de Claude…",
    "menu.addCodex": "Añadir cuenta de Codex…", "menu.hideColumn": "Ocultar columna",
    "menu.noColumns": "Sin columnas", "menu.showHidden": "Mostrar columnas ocultas",
    "menu.renameColumn": "Renombrar columna",
    "rename.title": "Nombre de la columna",
    "rename.hint": "Cómo se titula esta columna. Déjalo vacío para volver a «%@».",
    "common.save": "Guardar",
    "menu.hotKey": "Atajo: %@", "menu.hotKey.change": "Cambiar…",
    "menu.hotKey.standard": "Predeterminado (⌘P)", "menu.hotKey.disable": "Desactivar",
    "menu.loginItem": "Abrir al iniciar sesión", "menu.quit": "Salir",
    "hotkey.disabled": "desactivado", "hotkey.recorder.title": "Atajo",
    "hotkey.recorder.hint": "Pulsa una combinación — con ⌘, ⌥ o ⌃.",
    "hotkey.recorder.save": "Guardar",
    "hotkey.taken.title": "%@ ya está ocupado",
    "hotkey.taken.body": "Otra app ya lo usa. Tu ajuste anterior no ha cambiado.",
    "common.ok": "OK", "common.cancel": "Cancelar",
    "setup.claude.title": "Nueva cuenta de Claude",
    "setup.codex.title": "Nueva cuenta de Codex",
    "setup.profile.hint": "Elige un nombre corto para esta cuenta — por ejemplo work o personal. Será el título de la columna, y el CLI guardará ahí sus ajustes en una carpeta con ese nombre.",
    "setup.profile.terminal": "Tras pulsar «Crear» se abrirá el Terminal — inicia sesión allí.",
    "setup.profile.folder": "Carpeta: %@",
    "setup.profile.badChars": "Solo letras latinas, dígitos, guion y guion bajo.",
    "setup.profile.exists": "Ya existe un perfil con ese nombre.",
    "setup.create": "Crear", "setup.badName.title": "Nombre de perfil no válido",
    "setup.badName.body": "Solo letras latinas, dígitos, guion y guion bajo. El nombre no puede estar vacío ni repetido.",
    "setup.failed.title": "No se ha podido crear el perfil",
    "setup.missing.title": "No se ha encontrado %@",
    "setup.missing.body": "Instala el CLI e inténtalo de nuevo:\\n\\n%@",
    "setup.script.profile": "Perfil: %@",
    "setup.script.hint": "Inicia sesion y cierra esta ventana.",
    "loginItem.failed.title": "No se ha podido cambiar el inicio de sesión",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "error de red", "error.timeout": "tiempo agotado",
    "error.noHTTP": "sin respuesta HTTP", "error.http": "HTTP %d",
    "error.parse": "respuesta ilegible",
    "error.unknownSource": "origen desconocido", "error.noProvider": "sin proveedor",
    "error.unreachable": "red no disponible",
}

T["it"] = {
    "reset.days": "Reset tra %1$d g %2$d h",
    "reset.hours": "Reset tra %1$d h %2$d min",
    "reset.minutes": "Reset tra %d min",
    "reset.imminent": "Reset imminente",
    "age.justNow": "poco fa",
    "age.seconds": "%d s fa", "age.minutes": "%d min fa",
    "age.hours": "%d h fa", "age.days": "%d g fa",
    "window.fiveHour": "Finestra da 5 h", "window.week": "Finestra settimanale",
    "window.hours": "Finestra da %d h", "window.days": "Finestra da %d g",
    "window.generic": "Finestra di limite", "format.percent": "%d%%",
    "column.updating": "aggiornamento…", "column.stale": "dati di %@",
    "column.reauth.claude": "riautenticazione: avvia claude",
    "column.reauth.codex": "riautenticazione: avvia codex",
    "panel.updated": "Aggiornato %@", "panel.noData": "Ancora nessun dato",
    "panel.refresh.help": "Aggiorna tutte le colonne",
    "panel.empty.title": "Nessun account",
    "panel.empty.hint": "Clic destro → «Aggiungi account Claude…» o «Aggiungi account Codex…»",
    "panel.hidden.title": "Tutte le colonne nascoste",
    "panel.hidden.hint": "Clic destro → «Mostra colonne nascoste»",
    "menu.refresh": "Aggiorna", "menu.addClaude": "Aggiungi account Claude…",
    "menu.addCodex": "Aggiungi account Codex…", "menu.hideColumn": "Nascondi colonna",
    "menu.noColumns": "Nessuna colonna", "menu.showHidden": "Mostra colonne nascoste",
    "menu.renameColumn": "Rinomina colonna",
    "rename.title": "Nome della colonna",
    "rename.hint": "Come si chiama questa colonna. Lascia vuoto per tornare a «%@».",
    "common.save": "Salva",
    "menu.hotKey": "Scorciatoia: %@", "menu.hotKey.change": "Modifica…",
    "menu.hotKey.standard": "Predefinita (⌘P)", "menu.hotKey.disable": "Disattiva",
    "menu.loginItem": "Avvia all’accesso", "menu.quit": "Esci",
    "hotkey.disabled": "disattivata", "hotkey.recorder.title": "Scorciatoia",
    "hotkey.recorder.hint": "Premi una combinazione — con ⌘, ⌥ o ⌃.",
    "hotkey.recorder.save": "Salva",
    "hotkey.taken.title": "%@ è già in uso",
    "hotkey.taken.body": "Un’altra app lo usa già. L’impostazione precedente resta invariata.",
    "common.ok": "OK", "common.cancel": "Annulla",
    "setup.claude.title": "Nuovo account Claude",
    "setup.codex.title": "Nuovo account Codex",
    "setup.profile.hint": "Scegli un nome breve per questo account — per esempio work o personal. Diventerà il titolo della colonna e la CLI terrà le sue impostazioni in una cartella con quel nome.",
    "setup.profile.terminal": "Dopo «Crea» si apre il Terminale — accedi da lì.",
    "setup.profile.folder": "Cartella: %@",
    "setup.profile.badChars": "Solo lettere latine, cifre, trattino e trattino basso.",
    "setup.profile.exists": "Esiste già un profilo con questo nome.",
    "setup.create": "Crea", "setup.badName.title": "Nome profilo non valido",
    "setup.badName.body": "Solo lettere latine, cifre, trattino e trattino basso. Il nome non può essere vuoto o già usato.",
    "setup.failed.title": "Impossibile creare il profilo",
    "setup.missing.title": "Impossibile trovare %@",
    "setup.missing.body": "Installa la CLI e riprova:\\n\\n%@",
    "setup.script.profile": "Profilo: %@",
    "setup.script.hint": "Accedi, poi chiudi questa finestra.",
    "loginItem.failed.title": "Impossibile modificare l’avvio all’accesso",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "errore di rete", "error.timeout": "timeout",
    "error.noHTTP": "nessuna risposta HTTP", "error.http": "HTTP %d",
    "error.parse": "risposta non leggibile",
    "error.unknownSource": "origine sconosciuta", "error.noProvider": "nessun provider",
    "error.unreachable": "rete non disponibile",
}

T["pt-BR"] = {
    "reset.days": "Redefine em %1$d d %2$d h",
    "reset.hours": "Redefine em %1$d h %2$d min",
    "reset.minutes": "Redefine em %d min",
    "reset.imminent": "Redefinindo agora",
    "age.justNow": "agora mesmo",
    "age.seconds": "há %d s", "age.minutes": "há %d min",
    "age.hours": "há %d h", "age.days": "há %d d",
    "window.fiveHour": "Janela de 5 h", "window.week": "Janela semanal",
    "window.hours": "Janela de %d h", "window.days": "Janela de %d d",
    "window.generic": "Janela de limite", "format.percent": "%d%%",
    "column.updating": "atualizando…", "column.stale": "dados de %@",
    "column.reauth.claude": "reautenticar: rode claude",
    "column.reauth.codex": "reautenticar: rode codex",
    "panel.updated": "Atualizado %@", "panel.noData": "Ainda sem dados",
    "panel.refresh.help": "Atualizar todas as colunas",
    "panel.empty.title": "Sem contas",
    "panel.empty.hint": "Clique com o botão direito → “Adicionar conta Claude…” ou “Adicionar conta Codex…”",
    "panel.hidden.title": "Todas as colunas ocultas",
    "panel.hidden.hint": "Clique com o botão direito → “Mostrar colunas ocultas”",
    "menu.refresh": "Atualizar", "menu.addClaude": "Adicionar conta Claude…",
    "menu.addCodex": "Adicionar conta Codex…", "menu.hideColumn": "Ocultar coluna",
    "menu.noColumns": "Sem colunas", "menu.showHidden": "Mostrar colunas ocultas",
    "menu.renameColumn": "Renomear coluna",
    "rename.title": "Nome da coluna",
    "rename.hint": "Como esta coluna é rotulada. Deixe vazio para voltar a “%@”.",
    "common.save": "Salvar",
    "menu.hotKey": "Atalho: %@", "menu.hotKey.change": "Alterar…",
    "menu.hotKey.standard": "Padrão (⌘P)", "menu.hotKey.disable": "Desativar",
    "menu.loginItem": "Abrir ao iniciar sessão", "menu.quit": "Sair",
    "hotkey.disabled": "desativado", "hotkey.recorder.title": "Atalho",
    "hotkey.recorder.hint": "Pressione uma combinação — com ⌘, ⌥ ou ⌃.",
    "hotkey.recorder.save": "Salvar",
    "hotkey.taken.title": "%@ já está em uso",
    "hotkey.taken.body": "Outro app já usa esse atalho. Seu ajuste anterior foi mantido.",
    "common.ok": "OK", "common.cancel": "Cancelar",
    "setup.claude.title": "Nova conta Claude",
    "setup.codex.title": "Nova conta Codex",
    "setup.profile.hint": "Escolha um nome curto para esta conta — por exemplo work ou personal. Ele vira o título da coluna, e a CLI guarda as configurações numa pasta com esse nome.",
    "setup.profile.terminal": "Depois de “Criar”, o Terminal abre — faça login por lá.",
    "setup.profile.folder": "Pasta: %@",
    "setup.profile.badChars": "Apenas letras latinas, dígitos, hífen e sublinhado.",
    "setup.profile.exists": "Já existe um perfil com esse nome.",
    "setup.create": "Criar", "setup.badName.title": "Nome de perfil inválido",
    "setup.badName.body": "Apenas letras latinas, dígitos, hífen e sublinhado. O nome não pode estar vazio nem repetido.",
    "setup.failed.title": "Não foi possível criar o perfil",
    "setup.missing.title": "Não encontrei %@",
    "setup.missing.body": "Instale a CLI e tente de novo:\\n\\n%@",
    "setup.script.profile": "Perfil: %@",
    "setup.script.hint": "Faca login e feche esta janela.",
    "loginItem.failed.title": "Não foi possível mudar a abertura ao iniciar sessão",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "erro de rede", "error.timeout": "tempo esgotado",
    "error.noHTTP": "sem resposta HTTP", "error.http": "HTTP %d",
    "error.parse": "resposta ilegível",
    "error.unknownSource": "origem desconhecida", "error.noProvider": "sem provedor",
    "error.unreachable": "rede indisponível",
}

T["uk"] = {
    "reset.days": "Скидання через %1$d д %2$d год",
    "reset.hours": "Скидання через %1$d год %2$d хв",
    "reset.minutes": "Скидання через %d хв",
    "reset.imminent": "Скидання ось-ось",
    "age.justNow": "щойно",
    "age.seconds": "%d с тому", "age.minutes": "%d хв тому",
    "age.hours": "%d год тому", "age.days": "%d д тому",
    "window.fiveHour": "5-годинне вікно", "window.week": "Тижневе вікно",
    "window.hours": "%d-годинне вікно", "window.days": "%d-денне вікно",
    "window.generic": "Вікно ліміту", "format.percent": "%d %%",
    "column.updating": "оновлюю…", "column.stale": "дані %@",
    "column.reauth.claude": "re-auth: запусти claude",
    "column.reauth.codex": "re-auth: запусти codex",
    "panel.updated": "Оновлено %@", "panel.noData": "Даних ще немає",
    "panel.refresh.help": "Оновити всі колонки",
    "panel.empty.title": "Немає акаунтів",
    "panel.empty.hint": "Правий клік → «Додати акаунт Claude…» або «Додати акаунт Codex…»",
    "panel.hidden.title": "Усі колонки приховано",
    "panel.hidden.hint": "Правий клік → «Показати приховані колонки»",
    "menu.refresh": "Оновити", "menu.addClaude": "Додати акаунт Claude…",
    "menu.addCodex": "Додати акаунт Codex…", "menu.hideColumn": "Приховати колонку",
    "menu.noColumns": "Немає колонок", "menu.showHidden": "Показати приховані колонки",
    "menu.renameColumn": "Перейменувати колонку",
    "rename.title": "Назва колонки",
    "rename.hint": "Як підписати цю колонку. Порожньо — повернути «%@».",
    "common.save": "Зберегти",
    "menu.hotKey": "Гаряча клавіша: %@", "menu.hotKey.change": "Змінити…",
    "menu.hotKey.standard": "Стандартна (⌘P)", "menu.hotKey.disable": "Вимкнути",
    "menu.loginItem": "Запуск при вході", "menu.quit": "Вихід",
    "hotkey.disabled": "вимкнено", "hotkey.recorder.title": "Гаряча клавіша",
    "hotkey.recorder.hint": "Натисни комбінацію — обов’язково з ⌘, ⌥ або ⌃.",
    "hotkey.recorder.save": "Зберегти",
    "hotkey.taken.title": "Комбінація %@ зайнята",
    "hotkey.taken.body": "Її вже тримає інша програма. Попереднє налаштування лишилося без змін.",
    "common.ok": "Ок", "common.cancel": "Скасувати",
    "setup.claude.title": "Новий акаунт Claude",
    "setup.codex.title": "Новий акаунт Codex",
    "setup.profile.hint": "Придумай коротку назву для цього акаунта — наприклад work або personal. Вона стане заголовком колонки, а CLI триматиме налаштування в теці з такою назвою.",
    "setup.profile.terminal": "Після «Створити» відкриється Термінал — вхід робиться там.",
    "setup.profile.folder": "Тека: %@",
    "setup.profile.badChars": "Лише латиниця, цифри, дефіс і підкреслення.",
    "setup.profile.exists": "Профіль із такою назвою вже є.",
    "setup.create": "Створити", "setup.badName.title": "Погана назва профілю",
    "setup.badName.body": "Лише латиниця, цифри, дефіс і підкреслення. Назва не має бути порожньою або вже зайнятою.",
    "setup.failed.title": "Не вдалося створити профіль",
    "setup.missing.title": "Не знайшов %@",
    "setup.missing.body": "Встанови CLI і спробуй знову:\\n\\n%@",
    "setup.script.profile": "Профіль: %@",
    "setup.script.hint": "Увійди в акаунт, потім закрий це вікно.",
    "loginItem.failed.title": "Не вдалося змінити запуск при вході",
    "notification.title": "%1$@ — %2$d %%", "notification.body": "%1$@: %2$d %%",
    "error.network": "збій мережі", "error.timeout": "тайм-аут",
    "error.noHTTP": "немає HTTP-відповіді", "error.http": "HTTP %d",
    "error.parse": "не розібрав відповідь",
    "error.unknownSource": "невідоме джерело", "error.noProvider": "немає провайдера",
    "error.unreachable": "мережа недоступна",
}

T["pl"] = {
    "reset.days": "Reset za %1$d d %2$d godz.",
    "reset.hours": "Reset za %1$d godz. %2$d min",
    "reset.minutes": "Reset za %d min",
    "reset.imminent": "Reset za chwilę",
    "age.justNow": "przed chwilą",
    "age.seconds": "%d s temu", "age.minutes": "%d min temu",
    "age.hours": "%d godz. temu", "age.days": "%d d temu",
    "window.fiveHour": "Okno 5-godzinne", "window.week": "Okno tygodniowe",
    "window.hours": "Okno %d-godzinne", "window.days": "Okno %d-dniowe",
    "window.generic": "Okno limitu", "format.percent": "%d%%",
    "column.updating": "odświeżam…", "column.stale": "dane z %@",
    "column.reauth.claude": "re-auth: uruchom claude",
    "column.reauth.codex": "re-auth: uruchom codex",
    "panel.updated": "Zaktualizowano %@", "panel.noData": "Jeszcze brak danych",
    "panel.refresh.help": "Odśwież wszystkie kolumny",
    "panel.empty.title": "Brak kont",
    "panel.empty.hint": "Prawy przycisk → „Dodaj konto Claude…” lub „Dodaj konto Codex…”",
    "panel.hidden.title": "Wszystkie kolumny ukryte",
    "panel.hidden.hint": "Prawy przycisk → „Pokaż ukryte kolumny”",
    "menu.refresh": "Odśwież", "menu.addClaude": "Dodaj konto Claude…",
    "menu.addCodex": "Dodaj konto Codex…", "menu.hideColumn": "Ukryj kolumnę",
    "menu.noColumns": "Brak kolumn", "menu.showHidden": "Pokaż ukryte kolumny",
    "menu.renameColumn": "Zmień nazwę kolumny",
    "rename.title": "Nazwa kolumny",
    "rename.hint": "Jak podpisać tę kolumnę. Puste — wróć do „%@”.",
    "common.save": "Zapisz",
    "menu.hotKey": "Skrót: %@", "menu.hotKey.change": "Zmień…",
    "menu.hotKey.standard": "Domyślny (⌘P)", "menu.hotKey.disable": "Wyłącz",
    "menu.loginItem": "Uruchamiaj przy logowaniu", "menu.quit": "Zakończ",
    "hotkey.disabled": "wyłączony", "hotkey.recorder.title": "Skrót",
    "hotkey.recorder.hint": "Naciśnij kombinację — z ⌘, ⌥ lub ⌃.",
    "hotkey.recorder.save": "Zapisz",
    "hotkey.taken.title": "%@ jest już zajęty",
    "hotkey.taken.body": "Inna aplikacja już go używa. Poprzednie ustawienie pozostało bez zmian.",
    "common.ok": "OK", "common.cancel": "Anuluj",
    "setup.claude.title": "Nowe konto Claude",
    "setup.codex.title": "Nowe konto Codex",
    "setup.profile.hint": "Wybierz krótką nazwę dla tego konta — na przykład work albo personal. Stanie się nagłówkiem kolumny, a CLI będzie trzymać ustawienia w folderze o tej nazwie.",
    "setup.profile.terminal": "Po kliknięciu „Utwórz” otworzy się Terminal — zaloguj się tam.",
    "setup.profile.folder": "Folder: %@",
    "setup.profile.badChars": "Tylko litery łacińskie, cyfry, myślnik i podkreślenie.",
    "setup.profile.exists": "Profil o tej nazwie już istnieje.",
    "setup.create": "Utwórz", "setup.badName.title": "Zła nazwa profilu",
    "setup.badName.body": "Tylko litery łacińskie, cyfry, myślnik i podkreślenie. Nazwa nie może być pusta ani zajęta.",
    "setup.failed.title": "Nie udało się utworzyć profilu",
    "setup.missing.title": "Nie znaleziono %@",
    "setup.missing.body": "Zainstaluj CLI i spróbuj ponownie:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Zaloguj sie, potem zamknij to okno.",
    "loginItem.failed.title": "Nie udało się zmienić uruchamiania przy logowaniu",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "błąd sieci", "error.timeout": "przekroczono czas",
    "error.noHTTP": "brak odpowiedzi HTTP", "error.http": "HTTP %d",
    "error.parse": "nieczytelna odpowiedź",
    "error.unknownSource": "nieznane źródło", "error.noProvider": "brak dostawcy",
    "error.unreachable": "sieć niedostępna",
}

T["tr"] = {
    "reset.days": "%1$d g %2$d sa sonra sıfırlanır",
    "reset.hours": "%1$d sa %2$d dk sonra sıfırlanır",
    "reset.minutes": "%d dk sonra sıfırlanır",
    "reset.imminent": "Şimdi sıfırlanıyor",
    "age.justNow": "az önce",
    "age.seconds": "%d sn önce", "age.minutes": "%d dk önce",
    "age.hours": "%d sa önce", "age.days": "%d g önce",
    "window.fiveHour": "5 saatlik pencere", "window.week": "Haftalık pencere",
    "window.hours": "%d saatlik pencere", "window.days": "%d günlük pencere",
    "window.generic": "Limit penceresi", "format.percent": "%%%d",
    "column.updating": "yenileniyor…", "column.stale": "%@ verisi",
    "column.reauth.claude": "yeniden giriş: claude çalıştır",
    "column.reauth.codex": "yeniden giriş: codex çalıştır",
    "panel.updated": "Güncellendi %@", "panel.noData": "Henüz veri yok",
    "panel.refresh.help": "Tüm sütunları yenile",
    "panel.empty.title": "Hesap yok",
    "panel.empty.hint": "Sağ tık → “Claude hesabı ekle…” ya da “Codex hesabı ekle…”",
    "panel.hidden.title": "Tüm sütunlar gizli",
    "panel.hidden.hint": "Sağ tık → “Gizli sütunları göster”",
    "menu.refresh": "Yenile", "menu.addClaude": "Claude hesabı ekle…",
    "menu.addCodex": "Codex hesabı ekle…", "menu.hideColumn": "Sütunu gizle",
    "menu.noColumns": "Sütun yok", "menu.showHidden": "Gizli sütunları göster",
    "menu.renameColumn": "Sütunu yeniden adlandır",
    "rename.title": "Sütun adı",
    "rename.hint": "Bu sütunun etiketi. Boş bırakırsan “%@” geri gelir.",
    "common.save": "Kaydet",
    "menu.hotKey": "Kısayol: %@", "menu.hotKey.change": "Değiştir…",
    "menu.hotKey.standard": "Varsayılan (⌘P)", "menu.hotKey.disable": "Kapat",
    "menu.loginItem": "Girişte başlat", "menu.quit": "Çık",
    "hotkey.disabled": "kapalı", "hotkey.recorder.title": "Kısayol",
    "hotkey.recorder.hint": "Bir kombinasyona bas — ⌘, ⌥ ya da ⌃ içermeli.",
    "hotkey.recorder.save": "Kaydet",
    "hotkey.taken.title": "%@ zaten kullanılıyor",
    "hotkey.taken.body": "Başka bir uygulama onu tutuyor. Önceki ayarın değişmedi.",
    "common.ok": "Tamam", "common.cancel": "Vazgeç",
    "setup.claude.title": "Yeni Claude hesabı",
    "setup.codex.title": "Yeni Codex hesabı",
    "setup.profile.hint": "Bu hesap için kısa bir ad seç — örneğin work ya da personal. Sütun başlığı olacak ve CLI ayarlarını bu adı taşıyan klasörde tutacak.",
    "setup.profile.terminal": "“Oluştur”dan sonra Terminal açılır — girişi orada yap.",
    "setup.profile.folder": "Klasör: %@",
    "setup.profile.badChars": "Yalnızca Latin harfleri, rakam, tire ve alt çizgi.",
    "setup.profile.exists": "Bu adda bir profil zaten var.",
    "setup.create": "Oluştur", "setup.badName.title": "Geçersiz profil adı",
    "setup.badName.body": "Yalnızca Latin harfleri, rakam, tire ve alt çizgi. Ad boş ya da kullanımda olamaz.",
    "setup.failed.title": "Profil oluşturulamadı",
    "setup.missing.title": "%@ bulunamadı",
    "setup.missing.body": "CLI’yi kur ve tekrar dene:\\n\\n%@",
    "setup.script.profile": "Profil: %@",
    "setup.script.hint": "Giris yap, sonra bu pencereyi kapat.",
    "loginItem.failed.title": "Girişte başlatma değiştirilemedi",
    "notification.title": "%1$@ — %%%2$d", "notification.body": "%1$@: %%%2$d",
    "error.network": "ağ hatası", "error.timeout": "zaman aşımı",
    "error.noHTTP": "HTTP yanıtı yok", "error.http": "HTTP %d",
    "error.parse": "yanıt çözümlenemedi",
    "error.unknownSource": "bilinmeyen kaynak", "error.noProvider": "sağlayıcı yok",
    "error.unreachable": "ağ kullanılamıyor",
}

T["ja"] = {
    "reset.days": "リセットまで %1$d日 %2$d時間",
    "reset.hours": "リセットまで %1$d時間 %2$d分",
    "reset.minutes": "リセットまで %d分",
    "reset.imminent": "まもなくリセット",
    "age.justNow": "たった今",
    "age.seconds": "%d秒前", "age.minutes": "%d分前",
    "age.hours": "%d時間前", "age.days": "%d日前",
    "window.fiveHour": "5時間ウィンドウ", "window.week": "週間ウィンドウ",
    "window.hours": "%d時間ウィンドウ", "window.days": "%d日ウィンドウ",
    "window.generic": "制限ウィンドウ", "format.percent": "%d%%",
    "column.updating": "更新中…", "column.stale": "%@のデータ",
    "column.reauth.claude": "再認証: claude を実行",
    "column.reauth.codex": "再認証: codex を実行",
    "panel.updated": "更新 %@", "panel.noData": "データがまだありません",
    "panel.refresh.help": "すべての列を更新",
    "panel.empty.title": "アカウントなし",
    "panel.empty.hint": "右クリック →「Claude アカウントを追加…」または「Codex アカウントを追加…」",
    "panel.hidden.title": "すべての列が非表示",
    "panel.hidden.hint": "右クリック →「非表示の列を表示」",
    "menu.refresh": "更新", "menu.addClaude": "Claude アカウントを追加…",
    "menu.addCodex": "Codex アカウントを追加…", "menu.hideColumn": "列を非表示",
    "menu.noColumns": "列がありません", "menu.showHidden": "非表示の列を表示",
    "menu.renameColumn": "列の名前を変更",
    "rename.title": "列の名前",
    "rename.hint": "この列の見出しです。空にすると「%@」に戻ります。",
    "common.save": "保存",
    "menu.hotKey": "ショートカット: %@", "menu.hotKey.change": "変更…",
    "menu.hotKey.standard": "デフォルト (⌘P)", "menu.hotKey.disable": "オフにする",
    "menu.loginItem": "ログイン時に起動", "menu.quit": "終了",
    "hotkey.disabled": "オフ", "hotkey.recorder.title": "ショートカット",
    "hotkey.recorder.hint": "組み合わせを押してください — ⌘、⌥、⌃ のいずれかが必要です。",
    "hotkey.recorder.save": "保存",
    "hotkey.taken.title": "%@ は使用中です",
    "hotkey.taken.body": "他のアプリが使っています。以前の設定のままです。",
    "common.ok": "OK", "common.cancel": "キャンセル",
    "setup.claude.title": "新しい Claude アカウント",
    "setup.codex.title": "新しい Codex アカウント",
    "setup.profile.hint": "このアカウントの短い名前を決めてください（例: work、personal）。列の見出しになり、CLI はその名前のフォルダに設定を保存します。",
    "setup.profile.terminal": "「作成」を押すとターミナルが開きます。ログインはそこで行います。",
    "setup.profile.folder": "フォルダ: %@",
    "setup.profile.badChars": "半角英字・数字・ハイフン・アンダースコアのみ。",
    "setup.profile.exists": "同じ名前のプロファイルがすでにあります。",
    "setup.create": "作成", "setup.badName.title": "プロファイル名が不正です",
    "setup.badName.body": "半角英字・数字・ハイフン・アンダースコアのみ。空や既存の名前は使えません。",
    "setup.failed.title": "プロファイルを作成できませんでした",
    "setup.missing.title": "%@ が見つかりません",
    "setup.missing.body": "CLI をインストールして再試行してください:\\n\\n%@",
    "setup.script.profile": "プロファイル: %@",
    "setup.script.hint": "ログインしたら、このウインドウを閉じてください。",
    "loginItem.failed.title": "ログイン時の起動を変更できませんでした",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "ネットワークエラー", "error.timeout": "タイムアウト",
    "error.noHTTP": "HTTP 応答なし", "error.http": "HTTP %d",
    "error.parse": "応答を解析できません",
    "error.unknownSource": "不明なソース", "error.noProvider": "プロバイダなし",
    "error.unreachable": "ネットワークに接続できません",
}

T["ko"] = {
    "reset.days": "%1$d일 %2$d시간 후 초기화",
    "reset.hours": "%1$d시간 %2$d분 후 초기화",
    "reset.minutes": "%d분 후 초기화",
    "reset.imminent": "곧 초기화",
    "age.justNow": "방금",
    "age.seconds": "%d초 전", "age.minutes": "%d분 전",
    "age.hours": "%d시간 전", "age.days": "%d일 전",
    "window.fiveHour": "5시간 창", "window.week": "주간 창",
    "window.hours": "%d시간 창", "window.days": "%d일 창",
    "window.generic": "한도 창", "format.percent": "%d%%",
    "column.updating": "새로고침 중…", "column.stale": "%@ 데이터",
    "column.reauth.claude": "재인증: claude 실행",
    "column.reauth.codex": "재인증: codex 실행",
    "panel.updated": "업데이트 %@", "panel.noData": "아직 데이터 없음",
    "panel.refresh.help": "모든 열 새로고침",
    "panel.empty.title": "계정 없음",
    "panel.empty.hint": "오른쪽 클릭 → ‘Claude 계정 추가…’ 또는 ‘Codex 계정 추가…’",
    "panel.hidden.title": "모든 열 숨김",
    "panel.hidden.hint": "오른쪽 클릭 → ‘숨긴 열 보기’",
    "menu.refresh": "새로고침", "menu.addClaude": "Claude 계정 추가…",
    "menu.addCodex": "Codex 계정 추가…", "menu.hideColumn": "열 숨기기",
    "menu.noColumns": "열 없음", "menu.showHidden": "숨긴 열 보기",
    "menu.renameColumn": "열 이름 변경",
    "rename.title": "열 이름",
    "rename.hint": "이 열의 제목입니다. 비우면 ‘%@’ 로 돌아갑니다.",
    "common.save": "저장",
    "menu.hotKey": "단축키: %@", "menu.hotKey.change": "변경…",
    "menu.hotKey.standard": "기본값 (⌘P)", "menu.hotKey.disable": "끄기",
    "menu.loginItem": "로그인 시 실행", "menu.quit": "종료",
    "hotkey.disabled": "꺼짐", "hotkey.recorder.title": "단축키",
    "hotkey.recorder.hint": "조합을 누르세요 — ⌘, ⌥ 또는 ⌃ 가 필요합니다.",
    "hotkey.recorder.save": "저장",
    "hotkey.taken.title": "%@ 은(는) 이미 사용 중입니다",
    "hotkey.taken.body": "다른 앱이 사용 중입니다. 이전 설정이 그대로 유지됩니다.",
    "common.ok": "확인", "common.cancel": "취소",
    "setup.claude.title": "새 Claude 계정",
    "setup.codex.title": "새 Codex 계정",
    "setup.profile.hint": "이 계정의 짧은 이름을 정하세요 — 예를 들어 work 또는 personal. 열 제목이 되고, CLI 는 그 이름의 폴더에 설정을 저장합니다.",
    "setup.profile.terminal": "‘생성’을 누르면 터미널이 열립니다. 로그인은 거기서 하세요.",
    "setup.profile.folder": "폴더: %@",
    "setup.profile.badChars": "영문자, 숫자, 하이픈, 밑줄만 가능합니다.",
    "setup.profile.exists": "같은 이름의 프로파일이 이미 있습니다.",
    "setup.create": "생성", "setup.badName.title": "잘못된 프로파일 이름",
    "setup.badName.body": "영문자, 숫자, 하이픈, 밑줄만 가능합니다. 비어 있거나 이미 사용 중이면 안 됩니다.",
    "setup.failed.title": "프로파일을 만들지 못했습니다",
    "setup.missing.title": "%@ 을(를) 찾지 못했습니다",
    "setup.missing.body": "CLI 를 설치하고 다시 시도하세요:\\n\\n%@",
    "setup.script.profile": "프로파일: %@",
    "setup.script.hint": "로그인한 다음 이 창을 닫으세요.",
    "loginItem.failed.title": "로그인 시 실행을 변경하지 못했습니다",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@: %2$d%%",
    "error.network": "네트워크 오류", "error.timeout": "시간 초과",
    "error.noHTTP": "HTTP 응답 없음", "error.http": "HTTP %d",
    "error.parse": "응답을 해석할 수 없음",
    "error.unknownSource": "알 수 없는 소스", "error.noProvider": "제공자 없음",
    "error.unreachable": "네트워크 사용 불가",
}

T["zh-Hans"] = {
    "reset.days": "%1$d 天 %2$d 小时后重置",
    "reset.hours": "%1$d 小时 %2$d 分钟后重置",
    "reset.minutes": "%d 分钟后重置",
    "reset.imminent": "即将重置",
    "age.justNow": "刚刚",
    "age.seconds": "%d 秒前", "age.minutes": "%d 分钟前",
    "age.hours": "%d 小时前", "age.days": "%d 天前",
    "window.fiveHour": "5 小时窗口", "window.week": "每周窗口",
    "window.hours": "%d 小时窗口", "window.days": "%d 天窗口",
    "window.generic": "限额窗口", "format.percent": "%d%%",
    "column.updating": "正在刷新…", "column.stale": "%@的数据",
    "column.reauth.claude": "重新认证：运行 claude",
    "column.reauth.codex": "重新认证：运行 codex",
    "panel.updated": "更新于 %@", "panel.noData": "暂无数据",
    "panel.refresh.help": "刷新所有列",
    "panel.empty.title": "没有账户",
    "panel.empty.hint": "右键点击 →「添加 Claude 账户…」或「添加 Codex 账户…」",
    "panel.hidden.title": "所有列已隐藏",
    "panel.hidden.hint": "右键点击 →「显示隐藏的列」",
    "menu.refresh": "刷新", "menu.addClaude": "添加 Claude 账户…",
    "menu.addCodex": "添加 Codex 账户…", "menu.hideColumn": "隐藏列",
    "menu.noColumns": "没有列", "menu.showHidden": "显示隐藏的列",
    "menu.renameColumn": "重命名列",
    "rename.title": "列名称",
    "rename.hint": "这一列的标题。留空则恢复为「%@」。",
    "common.save": "存储",
    "menu.hotKey": "快捷键：%@", "menu.hotKey.change": "更改…",
    "menu.hotKey.standard": "默认 (⌘P)", "menu.hotKey.disable": "关闭",
    "menu.loginItem": "登录时启动", "menu.quit": "退出",
    "hotkey.disabled": "已关闭", "hotkey.recorder.title": "快捷键",
    "hotkey.recorder.hint": "按下组合键 — 必须包含 ⌘、⌥ 或 ⌃。",
    "hotkey.recorder.save": "存储",
    "hotkey.taken.title": "%@ 已被占用",
    "hotkey.taken.body": "另一个 App 已占用它。之前的设置保持不变。",
    "common.ok": "好", "common.cancel": "取消",
    "setup.claude.title": "新的 Claude 账户",
    "setup.codex.title": "新的 Codex 账户",
    "setup.profile.hint": "为这个账户取一个简短的名字，例如 work 或 personal。它会成为列标题，CLI 也会把设置放在同名文件夹里。",
    "setup.profile.terminal": "点击「创建」后会打开「终端」，在那里登录。",
    "setup.profile.folder": "文件夹：%@",
    "setup.profile.badChars": "只能使用拉丁字母、数字、连字符和下划线。",
    "setup.profile.exists": "同名的配置已存在。",
    "setup.create": "创建", "setup.badName.title": "配置名称无效",
    "setup.badName.body": "只能使用拉丁字母、数字、连字符和下划线。名称不能为空或重复。",
    "setup.failed.title": "无法创建配置",
    "setup.missing.title": "找不到 %@",
    "setup.missing.body": "请安装 CLI 后重试：\\n\\n%@",
    "setup.script.profile": "配置：%@",
    "setup.script.hint": "登录后关闭此窗口。",
    "loginItem.failed.title": "无法更改登录时启动",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@：%2$d%%",
    "error.network": "网络错误", "error.timeout": "超时",
    "error.noHTTP": "没有 HTTP 响应", "error.http": "HTTP %d",
    "error.parse": "无法解析响应",
    "error.unknownSource": "来源未知", "error.noProvider": "没有提供方",
    "error.unreachable": "网络不可用",
}

T["zh-Hant"] = {
    "reset.days": "%1$d 天 %2$d 小時後重置",
    "reset.hours": "%1$d 小時 %2$d 分鐘後重置",
    "reset.minutes": "%d 分鐘後重置",
    "reset.imminent": "即將重置",
    "age.justNow": "剛剛",
    "age.seconds": "%d 秒前", "age.minutes": "%d 分鐘前",
    "age.hours": "%d 小時前", "age.days": "%d 天前",
    "window.fiveHour": "5 小時視窗", "window.week": "每週視窗",
    "window.hours": "%d 小時視窗", "window.days": "%d 天視窗",
    "window.generic": "限額視窗", "format.percent": "%d%%",
    "column.updating": "更新中…", "column.stale": "%@的資料",
    "column.reauth.claude": "重新認證：執行 claude",
    "column.reauth.codex": "重新認證：執行 codex",
    "panel.updated": "更新於 %@", "panel.noData": "尚無資料",
    "panel.refresh.help": "重新整理所有欄",
    "panel.empty.title": "沒有帳號",
    "panel.empty.hint": "右鍵點按 →「加入 Claude 帳號…」或「加入 Codex 帳號…」",
    "panel.hidden.title": "所有欄皆已隱藏",
    "panel.hidden.hint": "右鍵點按 →「顯示隱藏的欄」",
    "menu.refresh": "重新整理", "menu.addClaude": "加入 Claude 帳號…",
    "menu.addCodex": "加入 Codex 帳號…", "menu.hideColumn": "隱藏欄",
    "menu.noColumns": "沒有欄", "menu.showHidden": "顯示隱藏的欄",
    "menu.renameColumn": "重新命名欄",
    "rename.title": "欄名稱",
    "rename.hint": "這一欄的標題。留空則恢復為「%@」。",
    "common.save": "儲存",
    "menu.hotKey": "快速鍵：%@", "menu.hotKey.change": "更改…",
    "menu.hotKey.standard": "預設 (⌘P)", "menu.hotKey.disable": "關閉",
    "menu.loginItem": "登入時啟動", "menu.quit": "結束",
    "hotkey.disabled": "已關閉", "hotkey.recorder.title": "快速鍵",
    "hotkey.recorder.hint": "按下組合鍵 — 必須包含 ⌘、⌥ 或 ⌃。",
    "hotkey.recorder.save": "儲存",
    "hotkey.taken.title": "%@ 已被佔用",
    "hotkey.taken.body": "另一個 App 已佔用它。先前的設定保持不變。",
    "common.ok": "好", "common.cancel": "取消",
    "setup.claude.title": "新的 Claude 帳號",
    "setup.codex.title": "新的 Codex 帳號",
    "setup.profile.hint": "為這個帳號取一個簡短的名稱，例如 work 或 personal。它會成為欄標題，CLI 也會把設定放在同名檔案夾裡。",
    "setup.profile.terminal": "點按「製作」後會開啟「終端機」，請在那裡登入。",
    "setup.profile.folder": "檔案夾：%@",
    "setup.profile.badChars": "僅能使用拉丁字母、數字、連字號和底線。",
    "setup.profile.exists": "同名的設定檔已存在。",
    "setup.create": "製作", "setup.badName.title": "設定檔名稱無效",
    "setup.badName.body": "僅能使用拉丁字母、數字、連字號和底線。名稱不能空白或重複。",
    "setup.failed.title": "無法製作設定檔",
    "setup.missing.title": "找不到 %@",
    "setup.missing.body": "請安裝 CLI 後再試一次：\\n\\n%@",
    "setup.script.profile": "設定檔：%@",
    "setup.script.hint": "登入後請關閉此視窗。",
    "loginItem.failed.title": "無法更改登入時啟動",
    "notification.title": "%1$@ — %2$d%%", "notification.body": "%1$@：%2$d%%",
    "error.network": "網路錯誤", "error.timeout": "逾時",
    "error.noHTTP": "沒有 HTTP 回應", "error.http": "HTTP %d",
    "error.parse": "無法解析回應",
    "error.unknownSource": "來源不明", "error.noProvider": "沒有提供者",
    "error.unreachable": "網路無法使用",
}


# Уведомления о сбросе окна. Держим отдельным словарём: строки notification.*
# у многих языков совпадают дословно, и точечная правка каждой таблицы была бы
# неоднозначной. Оба ключа несут ровно один «%@» — спецификаторы совпадают везде.
_RESET = {
    "en":      ("%@ — limit reset",          "%@ is available again"),
    "ru":      ("%@ — лимит сброшен",         "%@ снова доступно"),
    "de":      ("%@ — Limit zurückgesetzt",   "%@ ist wieder verfügbar"),
    "fr":      ("%@ — limite réinitialisée",  "%@ est de nouveau disponible"),
    "es":      ("%@ — límite reiniciado",     "%@ vuelve a estar disponible"),
    "it":      ("%@ — limite azzerato",       "%@ è di nuovo disponibile"),
    "pt-BR":   ("%@ — limite redefinido",     "%@ está disponível de novo"),
    "uk":      ("%@ — ліміт скинуто",         "%@ знову доступне"),
    "pl":      ("%@ — limit zresetowany",     "%@ znów dostępne"),
    "tr":      ("%@ — limit sıfırlandı",      "%@ yeniden kullanılabilir"),
    "ja":      ("%@ — 制限リセット",           "%@ が再び利用可能です"),
    "ko":      ("%@ — 한도 초기화",            "%@ 다시 사용 가능"),
    "zh-Hans": ("%@ — 限额已重置",            "%@ 重新可用"),
    "zh-Hant": ("%@ — 限額已重置",            "%@ 重新可用"),
}
for _lang, (_title, _body) in _RESET.items():
    T[_lang]["notification.reset.title"] = _title
    T[_lang]["notification.reset.body"] = _body


# Строки статистики под окнами. Без спецификаторов — подставляется только
# готовое число, поэтому проверка форматов их не касается.
_STATS = {
    "en":      ("Credits", "unlimited", "Early resets", "Extra usage"),
    "ru":      ("Кредиты", "без лимита", "Досрочные сбросы", "Расход сверх лимита"),
    "de":      ("Guthaben", "unbegrenzt", "Vorzeitige Resets", "Zusatzverbrauch"),
    "fr":      ("Crédits", "illimité", "Réinit. anticipées", "Usage supplémentaire"),
    "es":      ("Créditos", "ilimitado", "Reinicios anticipados", "Uso adicional"),
    "it":      ("Crediti", "illimitato", "Reset anticipati", "Uso aggiuntivo"),
    "pt-BR":   ("Créditos", "ilimitado", "Redefinições antecipadas", "Uso adicional"),
    "uk":      ("Кредити", "без ліміту", "Дострокові скидання", "Витрати понад ліміт"),
    "pl":      ("Kredyty", "bez limitu", "Wcześniejsze resety", "Zużycie ponad limit"),
    "tr":      ("Krediler", "sınırsız", "Erken sıfırlamalar", "Ek kullanım"),
    "ja":      ("クレジット", "無制限", "早期リセット", "追加利用"),
    "ko":      ("크레딧", "무제한", "조기 초기화", "추가 사용"),
    "zh-Hans": ("额度", "无限制", "提前重置", "额外用量"),
    "zh-Hant": ("額度", "無限制", "提前重置", "額外用量"),
}
for _lang, (_credits, _unlimited, _resets, _extra) in _STATS.items():
    T[_lang]["stat.credits"] = _credits
    T[_lang]["stat.unlimited"] = _unlimited
    T[_lang]["stat.resetCredits"] = _resets
    T[_lang]["stat.extraUsage"] = _extra


# Прогноз исчерпания: «упрёшься в 100 % примерно тогда-то». Один «%@» —
# готовая строка времени (Format.resetAbsolute), спецификатор совпадает везде.
_BURN = {
    "en":      "full ≈ %@",
    "ru":      "предел ≈ %@",
    "de":      "voll ≈ %@",
    "fr":      "plein ≈ %@",
    "es":      "lleno ≈ %@",
    "it":      "pieno ≈ %@",
    "pt-BR":   "cheio ≈ %@",
    "uk":      "межа ≈ %@",
    "pl":      "limit ≈ %@",
    "tr":      "dolum ≈ %@",
    "ja":      "上限 ≈ %@",
    "ko":      "한도 ≈ %@",
    "zh-Hans": "上限 ≈ %@",
    "zh-Hant": "上限 ≈ %@",
}
for _lang, _text in _BURN.items():
    T[_lang]["burn.limitAt"] = _text


def main():
    keys = [key for _, group in ORDER for key in group]
    base = T["en"]

    missing_report = []
    for language, table in T.items():
        absent = [key for key in keys if key not in table]
        extra = [key for key in table if key not in keys]
        if absent:
            missing_report.append("%s: нет ключей %s" % (language, ", ".join(absent)))
        if extra:
            missing_report.append("%s: лишние ключи %s" % (language, ", ".join(extra)))
    if missing_report:
        raise SystemExit("\n".join(missing_report))

    for language, table in sorted(T.items()):
        directory = os.path.join("Resources", language + ".lproj")
        os.makedirs(directory, exist_ok=True)
        lines = ["/* NotchLimits — %s. Собрано Tools/make-strings.py */" % language]
        for title, group in ORDER:
            lines.append("")
            lines.append("// " + title)
            for key in group:
                value = table.get(key, base[key]).replace('"', '\\"')
                lines.append('"%s" = "%s";' % (key, value))
        path = os.path.join(directory, "Localizable.strings")
        with io.open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines) + "\n")
        print("%-8s %d ключей" % (language, len(keys)))

    print("языков: %d" % len(T))


if __name__ == "__main__":
    main()
